/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  NTL
 * Created: Jun 2, 2017
 */

/* Luong giac */


/* To hop - xac suat */
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH001','Mạnh và Lâm cùng tham gia kỳ thi THPT Quốc Gia 2016 năm 2016, Ngoài thi ba môn Toán, Văn, Anh bắt buộc thì Mạnh và Lâm đều đăng ký thêm 2 môn tự chọn khác trong ba môn: Vật lý, Hóa, Sinh dưới hình thức trắc nghiệm  để xét tuyển vào Đại học, Cao đẳng. Mỗi môn tự chọn trắc nghiệm có 6 mã đề thi khác nhau, mã đề thi của các môn khác nhau là khác nhau. Tính xác suất để Mạnh và Lâm chỉ có chung  đúng một môn tự chọn và một mã đề thi.','$P= \\frac{1}{6}$','$P= \\frac{1}{9}$','$P= \\frac{1}{54}$','$P= \\frac{1}{216}$','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH002','Đội văn nghệ của một lớp có 5 bạn nam và 7 bạn nữ. Chọn ngẫu nhiên 5 bạn tham gia biểu diễn, tìm xác suất để trong 5 bạn được chọn có cả nam và nữ, đồng thời số bạn nam nhiều hơn số bạn nữ.','$P= \\frac{245}{729}$','$P= \\frac{210}{729}$','$P= 1 - \\frac{245}{729}$','$P=1- \\frac{210}{729}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH003','Có 30 tấm thẻ đánh số từ 1 đến 30. Chọn ngẫu nhiên ra 10 tấm thẻ. Tìm xác suất để có 5 tấm thẻ mang số lẻ, 5 tấm thẻ mang số chẵn, trong đó chỉ có đúng 1 tấm thẻ  mang số chia hết cho 10','$P= \\frac{C^{10}_{15} C^{4}_{12}C^{1}_{3}}{C^{5}_{30}}$','$P= \\frac{C^{5}_{15} C^{1}_{12}}{C^{10}_{30}}$','$P= \\frac{C^{5}_{15} C^{3}_{12}C^{1}_{3}}{C^{10}_{30}}$','$P= \\frac{C^{5}_{15} C^{4}_{12}C^{1}_{3}}{C^{10}_{30}}$','D','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH004','Chị Mai ra chợ mua 4 quả cam, 3 quả lê, 6 quả quýt, 1 quả bưởi và 2 quả thanh long. Chị Mai chọn 8 quả trong các quả mua về để bày thành mâm ngũ quả ngày tết. Tính xác suất  để mâm ngũ quả  của Chị Mai bày có đủ các loại quả mà chị mua về trong đó có ít nhất 3 quả cam.','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{2}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{3}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{3}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{2}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','A','tohop','xs ','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH005','Một chiếc hộp đựng 6 cái bút màu xanh, 6 cái bút màu đen, 5 cái bút màu tìm và 3 cái bút màu đỏ. Lấy ngẫu nhiên ra 4 cái bút. Tính xác suất để lấy được ít nhất 2 bút cùng màu.','$P = 1 - \\frac{36}{323}$','$P =  \\frac{48}{323}$','$P =  \\frac{36}{323}$','$P = 1 - \\frac{48}{323}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH006','Một đội xây dựng gồm 3 kĩ sư, 7 công nhân lập một tổ công tác gồm 5 người. Hỏi có bao nhiêu các lập tổ công tác gồm 1 kĩ sư làm tổ trưởng, 1 công nhân làm tổ phó và 3 công nhân tổ viên.','360 cách ','120 cách ','240 cách','420 cách','D','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH007','Cho $n$ là số nguyên dương dương thỏa mãn $C^{n-3}_{n}+A^{4}_{n} = 1$. Khi đó hệ số của $x^5$ sau khi khai triển biểu thức $(x^n - x^2 +x+1)^n$ là :','-4','6','0','5','C','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH008','Một lớp học có 18 học sinh nam và 12 học sinh nữ. Cần chọn một ban chấp hành chi đoàn gồm 3 người trong đó có một bí thư, một phó bí thư và một ủy viên. Tính xác suất để chọn được một ban chấp hành mà bí thư và phó bí thư không cùng giới tính.','$P = \\frac{36}{245}','$P = \\frac{72}{145}','$P = \\frac{36}{145}','$P = \\frac{28}{24360}','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH009','Có bao nhiêu số tự nhiên có 7 chữ số khác nhau từng đôi một, trong đó chữ số 2 đứng liền chữ số 1 và 3','249','3204','2942','7440','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH010','Trong một hộp kín đựng 2 viên bi đỏ, 5 viên bi trắng và 7 viên bi vàng. Lấy ngẫu nhiên 4 viên bi, tìm xác suất để 4 viên bi lấy ra không có đủ cả ba màu. ','$P=\\frac{8}{13}$','$P=\\frac{8}{5}$','$P=\\frac{5}{8}$','$P=\\frac{5}{13}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH011','Cho hai đường thẳng a và b song song với nhau. Trên đường thẳng a có 5 điểm phân biệt và trên đường thẳng b có 10 điểm phân biệt. Hỏi có thể tạo được bao nhiêu tam giác có các đỉnh là các điểm trên hai đường thẳng a và b đã cho .','325','425','225','100','A','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH012','Tông các hệ số sau khi khai triển biểu thức nhị thức Newton của biểu thức $(x-6)^9$ là.','-1953125','163296','-3919104','-18144','A','tohop','newton','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH013','Tìm hệ số $x^4$ sau khi khai triển biểu thức $(1 +x + 4x^2)^10$.','4620','4354','2370','-6568','C','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH014','Một nhóm học sinh gồm 7 nam và 5 nữ. Chọn ngẫu nhiên 3 học sinh lên bảng giải bài tập. Tính xác suất để chọn được 3 học sinh có cả nam và nữ.','$P = \\frac{C^{1}_{7}C^{2}_{5}+C^{3}_{7}C^{0}_{5}}{C^{3}_{12}}$','$P = \\frac{C^{2}_{7}C^{1}_{5}+C^{2}_{7}C^{2}_{5}}{C^{3}_{12}}$','$P = \\frac{C^{1}_{7}C^{2}_{5}+C^{2}_{7}C^{1}_{5}}{C^{3}_{12}}$','$P = 1- \\frac{C^{1}_{7}C^{2}_{5}+C^{2}_{7}C^{1}_{5}}{C^{3}_{12}}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH015','Giá trị của biểu thức $P = \\frac{C^{1}_{2017}}{2} + \\frac{C^{2}_{2017}}{3} + \\frac{C^{3}_{2017}}{4} + ... + \\frac{C^{2017}_{2017}}{2018}$ bằng:','$P =\\frac{{2^{2017} - 2016}}{2018} $','$P =\\frac{{2^{2016} - 2017}}{2016} $','$P =\\frac{{2^{2017} - 2018}}{2017} $','$P =\\frac{{2^{2018} - 2019}}{2018} $','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH016','Hệ số không chứa $x$ sau khi khai triển nhị thức Newton của biểu thức $\\left(3 \\sqrt[3][x] - \\frac{5}{\\sqrt[5][x]\\right)^8$ là:','-510300','4725000','-4725000','510300','C','tohop','newton','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH017','Xếp ngẫu nhiên 3 học sinh nam và 2 học sinh nữ thành một hàng ngang. Tĩnh xác suất để có 2 học sinh nữ đứng cạnh nhau ','$P = 1 - \\frac{2!3!}{5!}$','$P = \\frac{2!3!}{5!}$','$P = \\frac{4 2!3!}{5!}$','$P = \\frac{2 1!4!}{5!}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH018','Cho 10 điểm phân biệt $A_1, A_2, A_3, ..., A_{10}$ trong đó có 4 điểm $A_1, A_2, A_3,A_4$ thẳng hàng, ngoài ra không có 3 điểm nào thawrg hàng. Hỏi có bao nhiêu tam giác có 3 đỉnh được lấy trong 10 điểm trên.','80 tam giác ','96 tam giác','60 tam giác','116 tam giác ','D','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH019','Một đoàn tàu có 3 toa chở khách ở sân ga. Biết rằng toa có ít nhất 4 chỗ trống. Có 4 vị khách từ sân ga lên tàu, mỗi người độc lập với nhau, chọn ngẫu nhiên một toa. Tính xác suất để 1 trong 3 toa có 4 vị khác nói trên','$P = \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{A^{3}_{4}}$','$P = 1 - \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{3^4}$','$P = \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{3^4}$','$P = 1- \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{A^{3}_{4}}$','C','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH020','Cho 1 hộp đựng 4 viên bi đỏ, 5 viên bi xanh, 7 viên bi vàng. Lấy ngẫu nhiên một lần 3 viên bi. Tính xác suất để trong 3 viên lấy ra có 2 màu','$P =\\frac{29}{80}$','$P =\\frac{17}{80}$','$P =\\frac{53}{80}$','$P =\\frac{31}{80}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH021','Cho $n$ là số nguyên dương dương thỏa mãn $C^{n-3}_{n} - C^{2}_{n-1} = C^{1}_{n-1}C^{n+2}_{n+3}$. Tính hệ số của số hạng chứa $x^11$ trong khi khai triển nhị thức Newton của biểu thức $f(x) = x^3(x^{n-8} - \\frac{n}{3x})^n$','$-4^7 C^{7}_{12}$','$4^8 C^{8}_{12}$','$4^7 C^{7}_{12}$','$-4^8 C^{8}_{12}$','B','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH022','Cho đa giác đều $n$ đỉnh, $n \\in N$ và $n \\geq 3$. Tìm n biết rằng đa giác có 135 đường chéo.','$n = 15$','$n = 27$','$n = 8$','$n = 18$','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH023','Tìm hệ số $x^5$ trong khai triển biểu thức $P =  x(1 - 2x)^n + x^2( 1+3x)^{2n}$ biết rằng $A^{2}_{n} - C^{n-1}_{n+1} = 5$','$-5432$','3320','432','4674','B','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH024','Từ các chữ số 0, 1, 2, 3, 5, 8 có thể lập được bao nhiêu số tự nhiên lẻ có bốn chữ số đôi một khác nhau và phải có mặt chữ số 3 ?','228 số','144 số','36 số','108 số','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH025','Hệ số của $x^3$ trong khai triển biểu thức  $left( x - \\frac{1}{x^2}\\right)^9 là:','-84','126','-9','36','D','tohop','newton','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH026','Trong các mệnh đề sau, mệnh đề nào là sai ?','$P_n = n!$','$C^{k}_{n} = \\frac{A^{k}_{n}}{k!}$','$A^{n}_{n} = 1$','$C^{0}_{n} = 1$','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH027','Tìm số hạng không chứa $x$ trong khai triển $f(x) = \\left( \\sqrt[3]{x} + \\frac{2}{\\sqrt{x}} \\right)^n$ biết rằng số nguyên dương $n$ thỏa mãn $C^{6}_{n} + 3C^{7}_{n} + 3C^{8}_{n} +C^{9}_{n} = 2 C^{8}_{n+2}$','$2^5C^{5}_{15}$','$2^6C^{5}_{15}$','$2^5C^{6}_{15}$','$2^6C^{6}_{15}$','D','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH028','Chọn ngẫu nhiên 1 số tự nhiên bé hơn 8, Khi đó: ','Gọi A là biến cố "Số được chọn là số nguyên tố" thì tập hợp các kết quả thuận lợi cho A là {2, 3, 5, 7}','Xác suất số được chọn lớn hơn 2 là $P = \\frac{5}{7}$','Xác suất số được chọn là hợp số là $P = \\frac{3}{7}$','Không gian mẫu là số phần tử của tập hợp {1, 2, 3, 4, 5, 6, 7}','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH029','Một hộp chứ 20 quả cầu giống nhau gồm 12 quả màu đỏ và 8 quả màu xanh. Lấy ngẫu nhiên (đồng thời) 3 quả. Tính xác suất để ít nhất có một quả màu xanh.','$P= 1- \\frac{A^{3}_{12}}{A^{3}_{20}}$','$P= 1- \\frac{C^{3}_{12}}{C^{3}_{20}}$','$P= \\frac{C^{3}_{12}}{C^{3}_{20}}$','$P= \\frac{A^{3}_{12}}{A^{3}_{20}}$','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH030','Đội học sinh giỏi cấp trường môn tiếng Anh trường THPT X theo từng khối là như sau: Khối 10 có 5 học sinh, khối 11 có 5 học sinh và khối 12 có 5 học sinh. Nhà trường cần chọn một đội tuyển gồm 10 học sinh tham gia thi IOE cấp tỉnh. Tính xác suất để đội lập được có học sinh cả 3 khối và nhiều nhất có 2 học sinh lớp 10.','$P = \\frac{450}{3003}$','$P = \\frac{1}{6}$','$P = \\frac{50}{3003}$','$P = \\frac{500}{3003}$','D','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH031','Gọi X là tập hợp các số tự nhiên gồm 6 chữ số đôi một khác nhau được tạo thành từ các chữ số 1, 2, 3, 4, 5, 6, 7, 8, 9. Chọn ngẫu nhiên một số từ tập hợp X. Tính xác suất để số được chọn chỉ có 3 số lẻ.','$P = \\frac{16}{42}$','$P = \\frac{16}{21}$','$P = \\frac{23}{42}$','$P = \\frac{10}{21}$','D','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH032','Cho tập hợp  E = {1; 2; 3; 4; 5; 6} và M là tập hợp gồm tất cả các số gồm hai chữ số phân biệt lập từ E. Lấy ngẫu nhiên một số thuộc M. Tính xác suất để tổng hai chữ số đó lớn hơn 7. ','$P = \\frac{7}{30}$','$P = \\frac{12}{30}$','$P = \\frac{2}{3}$','$P = \\frac{3}{5}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH033','Nhà trường tổ chức tham quan dã ngoại cho 10 thành viên tiêu biểu của Câu lạc bộ Toán học và 10 thành viên tiêu biểu của Câu lạc bộ tiếng Anh. Trong một trò chơi, ban tổ chức chọn ngẫu nhiên 5 thành viên tham gia trò chơi. Tính xác suất sao cho trong 5 thành viên được chọn , mỗi Câu lạc có ít nhất 1 thành viên.','$P= 1- \\frac{2C^{5}_{10}}{C^{5}_{20}}$','$P= \\frac{2C^{5}_{10}}{C^{5}_{20}}$','$P= \\frac{C^{5}_{10}}{C^{5}_{20}}$','$P= 1 - \\frac{C^{5}_{10}}{C^{5}_{20}}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH034','Trong khai triển nhị thức Newton của biểu thức $(x^3 - x - 2)^2017$ thì tổng các hệ số của $x^{2k+1}$ và k là số nguyên dương :','$2^{2017}$','$\\frac{2^{2017} + 2^{2016}}{2}$','$\\frac{2^{2017} - 2^{2016}}{2}$','$2^{2016}$','A','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH035','Tính tổng $S = 2^2C^{2}_{2010} - 3^2C^{3}_{2010} + 4^2C^{4}_{2010} - ... + 2010^2C^{2010}_{2010}$','$S = 2010$','$S = -C^{1005}_{2010}$','$S = 0$','$S = - 1005$','C','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH036','Tính tổng $S = C^{0}_{2016} + 2C^{1}_{2016} + 3C^{2}_{2016} + 4C^{3}_{2016} + ... + 2017C^{2016}_{2016}$','$S = 2016 . 2^{2015}$','$S = 2018 . 2^{2016}$','$S = 2015 . 2^{2016}$','$S = 2018 . 2^{2015}$','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH037','Đội văn nghệ của nhà trường 4 học sinh lớp 12A, 3 học sinh lớp 12B và 2 học sinh lớp 12C. Chọn ngẫu nhiên 5 học sinh từ đội văn nghệ để biểu diễn trong lễ bế giảng năm học. Tính xác suất sao cho lớp nào cũng có học sinh được chọn và có ít nhất 2 học sinh lớp 12A.','$P = \\frac{11}{21}$','$P = \\frac{78}{126}$','$P = \\frac{66}{126}$','$P = \\frac{13}{22}$','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH038','Trong đợt thi học sinh giỏi của trường THPT, môn Toán có 5 em đạt giải trong đó có 4 nam và 1 nữ, môn Văn có 5 em đạt giải trong đó có 1 nam và 4 nữ, môn Hóa học có 5 em đạt giải trong đó 2 nam và 3 nữ, môn vật lý có 5 em đạt giải trong đó có 3 nam và 2 nữ. Hỏi có bao nhiêu cách chọn mỗi môn một em học sinh để đi dự đại hội thi đua ? Tính xác suất để có cả học sinh nam và nữ để đi dự đại hội? ','$P = \\frac{576}{625}$','$P = \\frac{577}{625}$','$P = \\frac{49}{625}$','$P = \\frac{48}{625}$','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH039',' Trong một đợt kiểm tra về vệ sinh an toàn thực phẩm ngành y tế tại chợ X. Ban quản lý chợ lấy ra 15 mẫu thịt lợn trong đó có 4 mẫu ở quầy A, 5 mẫu ở quầy B, 6 mẫu ở quầy C. Mỗi mẫu thịt này có khối lượng như nhau và để trong các hộp kín có kích thước giống hệt nhau. Đoàn kiểm tra lấy ra ngẫu nhiên ba hộp để phân tích, kiểm tra xem trong hợp thịt lợn có chứa hóa chất "Super tạo nạc" (Clenbuterol) hay không. Tính xác suất để 3 hộp lấy ra có đủ 3 loại tịt ở quầy A, B, C.','$P = \\frac{24}{91}$','$P = \\frac{17}{24}$','$P = \\frac{24}{455}$','$P = \\frac{17}{91}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH040','Tìm hệ số số hạng chứ $x^5$ trong khai triển $(1 + 3x)^{2n}$ biết $A^{3}_{n} + 2A^{2}_{n} = 100$.','$ -6^5 C^{5}_{12}$','$ -3^5 C^{5}_{12}$','$ 3^5 C^{5}_{10}$','$ 6^5 C^{5}_{10}$','C','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH041','Một hộp đựng 9 tấm thẻ được đánh số từ 1 đến 9. Hỏi phải rút ít nhất bao nhiêu thẻ để xác suất có ít nhất một thẻ ghi số chia hết cho 4 phải lớn hơn $\\frac{5}{6}$','5 tấm thẻ','6 tấm thẻ','7 tấm thẻ','2 tấm thẻ','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH042','Một hộp đựng chứa 4 viên bi trắng, 5 viên bi đỏ và 6 viên bi xanh. Lấy ngẫu nhiên từ hộp ra 4 viên bi. Tính xác suất để 4 viên bi được chọn có đủ 3 màu và số bi đỏ nhiều nhất','$P = \\frac{5}{11}$','$P = \\frac{19}{91}$','$P = \\frac{16}{91}$','$P = \\frac{17}{91}$','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH043','Trong các phát biểu sau, phát biểu nào đúng ?','Hai biến cố xung khác là hai biến cố đối nhau','Hai biến cố đối lập có ít nhất một trong hai biến cố xảy ra.','Hai biến cố xung khác là hai biến cố cùng xảy ra.','Hai biến cố đối nhau là hai biến cố xung khắc.','D','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH044','Phát biểu nào sai khi nói về "phép thử ngẫu nhiên"?','Có thể xác định được tập hợp kết quả có thể xảy ra của phép thử đó','Kết quả của nó không đoán trước được.','Bao gồm tập hợp các "không gian mẫu" của phép thử','Là một thí nghiệm hoặc một hành động','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH045','Cho 100 tấm thẻ đánh số từ 1 đến 100, chọn ngẫu nhiên 3 thẻ. Tính xác suất để tổng các số ghi trên 3 thẻ được chọn là số chia hết cho 2.','$P = \\frac{5}{6}$','$P = \\frac{1}{2}$','$P = \\frac{5}{7}$','$P = \\frac{3}{4}$','B','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH046','Đoàn trường có 18 chi đoàn học sinh gồm 6 chi đoàn khối 10, 5 chi đoàn khối 11 và 7 chi đoàn khối 12. Nhân kỉ niệm "85 năm thành lập Đoàn thanh niên cộng sản Hồ Chí Minh". Đoàn trường cần chọn 4 bí thư chi đoàn từ các bí thứ trên để đi tham dự mít tinh ở Huyện đoàn. Tính xác suất để chọn được 4 bí thứ chi đoàn sao cho có đủ bí thư chi đoàn của ba khối.','$P = \\frac{68}{72}$','$P = \\frac{35}{72}$','$P = \\frac{35}{68}$','$P = 1- \\frac{35}{72}$','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH047','Cho tập hợp  A = {1; 2; 3; 4; 5; 6 ; 7}. Từ các phần tử của tập hợp A lập các số tự nhiên có 4 chữ số, các chữ số đôi một khác nhau, chọn ngẫu nhiên một số từ số mới lập đó. Tính xác suất để số được chọn có chữ số hàng nghìn nhỏ hơn 5.','$P = \\frac{2}{7}$','$P = \\frac{4}{7}$','$P = \\frac{5}{7}$','$P = \\frac{3}{7}$','B','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH048','Gọi S là tập hợp các số tự nhiên gồm 4 chữ số khác nhau được chọn từ các số 0, 1, 2, 3, 4, 5. Chọn ngẫu nhiên một số từ tập S, Tính xác suất để số được chọn có mặt ít nhất chữ số 1 hoặc chữ số 2','$P = \\frac{47}{50}$','$P = \\frac{3}{50}$','$P = \\frac{3}{25}$','$P = \\frac{3}{47}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH049','Có bao nhiêu số tự nhiên có 5 chữ số khác nhau mà trong mỗi số luôn luôn có mặt hai chữ số chẵn và ba chữ số lẻ.','11040 số','12000 số','960 số','13200 số','A','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH050','Quy tắc cộng còn có thể được phát biểu dưới dạng','Nếu A và B là hai tập hợp hữu hạn không hợp nhau thì số phần tử $A \\cup B$ bằng số phần tử của A cộng với số phần tử B','Nếu A và B là hai tập hợp hữu hạn không giao nhau thì số phần tử $A \\cap B$ bằng số phần tử của A cộng với số phần tử B','Nếu A và B là hai tập hợp hữu hạn không giao nhau thì số phần tử $A \\cup B$ bằng số phần tử của A cộng với số phần tử của B','Nếu A và B là hai tập hợp hữu hạn không hợp nhau thì số phần tử $A \\cap B$ bằng số phần tử của A cộng với số phần tử của B','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH051','Tìm hệ số của $x^5$ trong khai triển biểu thức $P = x(1- 2x)^n +x^2(1+3x)^{2n}$ biết rằng $A^{2}_{n} - C^{n - 1}_{n + 1} = 5$','3320','-4802','1549','-3032','A','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH052','Trong đợt tuyển chọn và gọi công nhân nhập ngũ năm 2016, xã A tuyển chọn được 10 người trong đó có một người tên Hùng và một người tên Dũng. Xã A cần chọn ra từ đó 6 người để thực hiện nghĩa vụ quân sự đợt này. Tính xác suất của biến số 6 người được chọn trong 10 người này không có mặt đồng thời cả Hùng và Dũng.','$P = 1 - \\frac{C^{4}{8}}{C^{6}{10}}$','$P = 1 - \\frac{C^{6}{8}}{C^{6}{10}}$','$P = \\frac{C^{4}{8}}{C^{6}{10}}$','$P = \\frac{C^{6}{8}}{C^{6}{10}}$','A','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH053','Tổ Toán-Tin của một trường gồm 10 giáo viên trong đó có 3 giáo viên nam, 7 giáo viên nữ. Tổ Lý -Hóa- Sinh của trường gồm 12 giáo viên trong đó có 3 giáo viên nam, 9 giáo viên nữ. Chọn ngẫu nhiên mỗi tổ 2 giáo viên đi chuyên đề. Tính xác suất sao cho các giáo viên được chọn có cả nam và nữ.','$P = \\frac{49}{66}$','$P = \\frac{17}{205}$','$P = \\frac{76}{205}$','$P = \\frac{17}{66}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH054','Trong khai triển nhị thức newton của biểu thức $(a + b)$','Tích số mũ của a và b là hằng số ','Tổng số mũ a và b luôn không đổi','Tổng số mũ của a và b nhỏ nhất khi và chỉ khi hai số mũ bằng nhau','Tích số mũ của a và b lớn nhất khi và chỉ khi hai số mũ bằng nhau ','B','tohop','newton','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH055','Một tổ có 15 học sinh trong đó có 9 học sinh nam và 6 học sinh nữ. Hỏi có bao nhiêu cách chia tổ thành 3 nhóm sao cho mỗi nhóm có đúng 3 học sinh nam và 2 học sinh nữ','$C^{3}{9}C^{2}{6}C^{4}{6}C^{3}{4}$ cách','$C^{3}{9}C^{4}{6}C^{2}{6}C^{2}{4}$ cách','$C^{4}{9}C^{2}{6}C^{4}{6}C^{2}{4}$ cách','$C^{3}{9}C^{2}{6}C^{3}{6}C^{2}{4}$ cách','D','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH056','Tìm số nguyên dương $n$ thỏa mãn $ A^{2}_{n} - 3C^{2}_{n} = 15 - 5n$','n = 5 hoặc n = 6 hoặc n = 12 ','n = 5 hoặc n = 6','n = 6','n =5','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH057','Tìm hệ số chứa x^2 trong khai triển nhị thứ Newton $\\left( x^2 + \\frac{2}{x} \\right)^n biết n là số nguyên dương tỏa mãn $3C^{3}_{n+1} - 3A^{2}_{n} = 52(n-1)$','$2^8 C^{8}_{13}$','$2^7 C^{7}_{13}$','$2^5 C^{5}_{13}$','$2^6 C^{6}_{13}$','A','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH058','Từ các số tự nhiên 1, 2, 3, 4 có thể lập được bao nhiêu số tự nhiên có 4 chữ số khác nhau?','$4^4$','24','1','42','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH059','Từ các số tự nhiên 1, 2, 3, 4 có thể lập được bao nhiêu số tự nhiên có 3 chữ số khác nhau?','12','6','4','24','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH060','Từ các số tự nhiên 1, 2, 3, 4, 5, 6 có thể lập được bao nhiêu số tự nhiên có 5 chữ số?','120','1','3125','600','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH061','Cho $A = {1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số chẵn có 5 chữ số ?','3888','360','15','120','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH062','Cho $A = {0, 1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số tự nhiên có 5 chữ số đôi một khác nhau ','2160','2520','21','5040','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH063','Cho $A = {0, 1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số lẻ có 5 chữ số đôi một khác nhau ','2520','900','1080','21','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH064','Từ các số 0, 1, 2, 3, 4, 5, 6 có thể lập được bao nhiêu số tự nhiên có 3 chữ số ','210','105','168','84','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH065','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong lớp','9880','59280','2300','455','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH066','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong đó có 1 học sinh nam và 2 học sinh nữ','5250','4500','2625','1500','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH067','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong đó có nhiều nhất 1 học sinh nam.','2625','455','2300','3080','D','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH068','Một nhóm học sinh có 4 nam và 3 nữ Có bao nhiêu cách chọn 3 bạn trong đó có đúng 1 bạn nữ?','8','18','28','38','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH069','Một nhóm học sinh có 6 bạn nam và 5 bạn nữ có bao nhiêu cách chọn ra 5 bạn trong đó có 3 bạn nam và 2 bạn nữ','462','2400','200','20','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH070','Một hộp đựng 5 viên bi màu xanh, 7 viên bi màu vàng. Có bao nhiêu các lấy ra 6 viên bi bất kỳ?','665280','924','7','942','B','tohop','tohop','0',NULL,'11','0');

/* Phep doi hinh */


/* Day so */


/* Gioi han */


/* HHKG */