/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  NTL
 * Created: Jun 2, 2017
 */

/* Luong giac */


/* To hop - xac suat */
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH001','Mạnh và Lâm cùng tham gia kỳ thi THPT Quốc Gia 2016 năm 2016, Ngoài thi ba môn Toán, Văn, Anh bắt buộc thì Mạnh và Lâm đều đăng ký thêm 2 môn tự chọn khác trong ba môn: Vật lý, Hóa, Sinh dưới hình thức trắc nghiệm  để xét tuyển vào Đại học, Cao đẳng. Mỗi môn tự chọn trắc nghiệm có 6 mã đề thi khác nhau, mã đề thi của các môn khác nhau là khác nhau. Tính xác suất để Mạnh và Lâm chỉ có chung  đúng một môn tự chọn và một mã đề thi.','$P= \\frac{1}{6}$','$P= \\frac{1}{9}$','$P= \\frac{1}{54}$','$P= \\frac{1}{216}$','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH002','Đội văn nghệ của một lớp có 5 bạn nam và 7 bạn nữ. Chọn ngẫu nhiên 5 bạn tham gia biểu diễn, tìm xác suất để trong 5 bạn được chọn có cả nam và nữ, đồng thời số bạn nam nhiều hơn số bạn nữ.','$P= \\frac{245}{729}$','$P= \\frac{210}{729}$','$P= 1 - \\frac{245}{729}$','$P=1- \\frac{210}{729}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH003','Có 30 tấm thẻ đánh số từ 1 đến 30. Chọn ngẫu nhiên ra 10 tấm thẻ. Tìm xác suất để có 5 tấm thẻ mang số lẻ, 5 tấm thẻ mang số chẵn, trong đó chỉ có đúng 1 tấm thẻ  mang số chia hết cho 10','$P= \\frac{C^{10}_{15} C^{4}_{12}C^{1}_{3}}{C^{5}_{30}}$','$P= \\frac{C^{5}_{15} C^{1}_{12}}{C^{10}_{30}}$','$P= \\frac{C^{5}_{15} C^{3}_{12}C^{1}_{3}}{C^{10}_{30}}$','$P= \\frac{C^{5}_{15} C^{4}_{12}C^{1}_{3}}{C^{10}_{30}}$','D','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH004','Chị Mai ra chợ mua 4 quả cam, 3 quả lê, 6 quả quýt, 1 quả bưởi và 2 quả thanh long. Chị Mai chọn 8 quả trong các quả mua về để bày thành mâm ngũ quả ngày tết. Tính xác suất  để mâm ngũ quả  của Chị Mai bày có đủ các loại quả mà chị mua về trong đó có ít nhất 3 quả cam.','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{2}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{3}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','$ P = \\frac{C^{4}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{1}_{2} + C^{3}_{4}C^{2}_{3}C^{3}_{6}C^{1}_{1}C^{1}_{2}+C^{3}_{4}C^{1}_{3}C^{2}_{6}C^{1}_{1}C^{1}_{2} + C^{2}_{4}C^{1}_{3}C^{1}_{6}C^{1}_{1}C^{2}_{2} }{C^{8}_{16}}$','A','tohop','xs ','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH005','Một chiếc hộp đựng 6 cái bút màu xanh, 6 cái bút màu đen, 5 cái bút màu tìm và 3 cái bút màu đỏ. Lấy ngẫu nhiên ra 4 cái bút. Tính xác suất để lấy được ít nhất 2 bút cùng màu.','$P = 1 - \\frac{36}{323}$','$P =  \\frac{48}{323}$','$P =  \\frac{36}{323}$','$P = 1 - \\frac{48}{323}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH006','Một đội xây dựng gồm 3 kĩ sư, 7 công nhân lập một tổ công tác gồm 5 người. Hỏi có bao nhiêu các lập tổ công tác gồm 1 kĩ sư làm tổ trưởng, 1 công nhân làm tổ phó và 3 công nhân tổ viên.','360 cách ','120 cách ','240 cách','420 cách','D','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH007','Cho $n$ là số nguyên dương dương thỏa mãn $C^{n-3}_{n}+A^{4}_{n} = 1$. Khi đó hệ số của $x^5$ sau khi khai triển biểu thức $(x^n - x^2 +x+1)^n$ là :','-4','6','0','5','C','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH008','Một lớp học có 18 học sinh nam và 12 học sinh nữ. Cần chọn một ban chấp hành chi đoàn gồm 3 người trong đó có một bí thư, một phó bí thư và một ủy viên. Tính xác suất để chọn được một ban chấp hành mà bí thư và phó bí thư không cùng giới tính.','$P = \\frac{36}{245}','$P = \\frac{72}{145}','$P = \\frac{36}{145}','$P = \\frac{28}{24360}','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH009','Có bao nhiêu số tự nhiên có 7 chữ số khác nhau từng đôi một, trong đó chữ số 2 đứng liền chữ số 1 và 3','249','3204','2942','7440','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH010','Trong một hộp kín đựng 2 viên bi đỏ, 5 viên bi trắng và 7 viên bi vàng. Lấy ngẫu nhiên 4 viên bi, tìm xác suất để 4 viên bi lấy ra không có đủ cả ba màu. ','$P=\\frac{8}{13}$','$P=\\frac{8}{5}$','$P=\\frac{5}{8}$','$P=\\frac{5}{13}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH011','Cho hai đường thẳng a và b song song với nhau. Trên đường thẳng a có 5 điểm phân biệt và trên đường thẳng b có 10 điểm phân biệt. Hỏi có thể tạo được bao nhiêu tam giác có các đỉnh là các điểm trên hai đường thẳng a và b đã cho .','325','425','225','100','A','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH012','Tông các hệ số sau khi khai triển biểu thức nhị thức Newton của biểu thức $(x-6)^9$ là.','-1953125','163296','-3919104','-18144','A','tohop','newton','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH013','Tìm hệ số $x^4$ sau khi khai triển biểu thức $(1 +x + 4x^2)^10$.','4620','4354','2370','-6568','C','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH014','Một nhóm học sinh gồm 7 nam và 5 nữ. Chọn ngẫu nhiên 3 học sinh lên bảng giải bài tập. Tính xác suất để chọn được 3 học sinh có cả nam và nữ.','$P = \\frac{C^{1}_{7}C^{2}_{5}+C^{3}_{7}C^{0}_{5}}{C^{3}_{12}}$','$P = \\frac{C^{2}_{7}C^{1}_{5}+C^{2}_{7}C^{2}_{5}}{C^{3}_{12}}$','$P = \\frac{C^{1}_{7}C^{2}_{5}+C^{2}_{7}C^{1}_{5}}{C^{3}_{12}}$','$P = 1- \\frac{C^{1}_{7}C^{2}_{5}+C^{2}_{7}C^{1}_{5}}{C^{3}_{12}}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH015','Giá trị của biểu thức $P = \\frac{C^{1}_{2017}}{2} + \\frac{C^{2}_{2017}}{3} + \\frac{C^{3}_{2017}}{4} + ... + \\frac{C^{2017}_{2017}}{2018}$ bằng:','$P =\\frac{{2^{2017} - 2016}}{2018} $','$P =\\frac{{2^{2016} - 2017}}{2016} $','$P =\\frac{{2^{2017} - 2018}}{2017} $','$P =\\frac{{2^{2018} - 2019}}{2018} $','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH016','Hệ số không chứa $x$ sau khi khai triển nhị thức Newton của biểu thức $\\left(3 \\sqrt[3][x] - \\frac{5}{\\sqrt[5][x]\\right)^8$ là:','-510300','4725000','-4725000','510300','C','tohop','newton','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH017','Xếp ngẫu nhiên 3 học sinh nam và 2 học sinh nữ thành một hàng ngang. Tĩnh xác suất để có 2 học sinh nữ đứng cạnh nhau ','$P = 1 - \\frac{2!3!}{5!}$','$P = \\frac{2!3!}{5!}$','$P = \\frac{4 2!3!}{5!}$','$P = \\frac{2 1!4!}{5!}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH018','Cho 10 điểm phân biệt $A_1, A_2, A_3, ..., A_{10}$ trong đó có 4 điểm $A_1, A_2, A_3,A_4$ thẳng hàng, ngoài ra không có 3 điểm nào thawrg hàng. Hỏi có bao nhiêu tam giác có 3 đỉnh được lấy trong 10 điểm trên.','80 tam giác ','96 tam giác','60 tam giác','116 tam giác ','D','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH019','Một đoàn tàu có 3 toa chở khách ở sân ga. Biết rằng toa có ít nhất 4 chỗ trống. Có 4 vị khách từ sân ga lên tàu, mỗi người độc lập với nhau, chọn ngẫu nhiên một toa. Tính xác suất để 1 trong 3 toa có 4 vị khác nói trên','$P = \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{A^{3}_{4}}$','$P = 1 - \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{3^4}$','$P = \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{3^4}$','$P = 1- \\frac{C^{3}_{4}C^{1}_{3}C^{1}_{2} }{A^{3}_{4}}$','C','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH020','Cho 1 hộp đựng 4 viên bi đỏ, 5 viên bi xanh, 7 viên bi vàng. Lấy ngẫu nhiên một lần 3 viên bi. Tính xác suất để trong 3 viên lấy ra có 2 màu','$P =\\frac{29}{80}$','$P =\\frac{17}{80}$','$P =\\frac{53}{80}$','$P =\\frac{31}{80}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH021','Cho $n$ là số nguyên dương dương thỏa mãn $C^{n-3}_{n} - C^{2}_{n-1} = C^{1}_{n-1}C^{n+2}_{n+3}$. Tính hệ số của số hạng chứa $x^11$ trong khi khai triển nhị thức Newton của biểu thức $f(x) = x^3(x^{n-8} - \\frac{n}{3x})^n$','$-4^7 C^{7}_{12}$','$4^8 C^{8}_{12}$','$4^7 C^{7}_{12}$','$-4^8 C^{8}_{12}$','B','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH022','Cho đa giác đều $n$ đỉnh, $n \\in N$ và $n \\geq 3$. Tìm n biết rằng đa giác có 135 đường chéo.','$n = 15$','$n = 27$','$n = 8$','$n = 18$','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH023','Tìm hệ số $x^5$ trong khai triển biểu thức $P =  x(1 - 2x)^n + x^2( 1+3x)^{2n}$ biết rằng $A^{2}_{n} - C^{n-1}_{n+1} = 5$','$-5432$','3320','432','4674','B','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH024','Từ các chữ số 0, 1, 2, 3, 5, 8 có thể lập được bao nhiêu số tự nhiên lẻ có bốn chữ số đôi một khác nhau và phải có mặt chữ số 3 ?','228 số','144 số','36 số','108 số','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH025','Hệ số của $x^3$ trong khai triển biểu thức  $left( x - \\frac{1}{x^2}\\right)^9 là:','-84','126','-9','36','D','tohop','newton','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH026','Trong các mệnh đề sau, mệnh đề nào là sai ?','$P_n = n!$','$C^{k}_{n} = \\frac{A^{k}_{n}}{k!}$','$A^{n}_{n} = 1$','$C^{0}_{n} = 1$','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH027','Tìm số hạng không chứa $x$ trong khai triển $f(x) = \\left( \\sqrt[3]{x} + \\frac{2}{\\sqrt{x}} \\right)^n$ biết rằng số nguyên dương $n$ thỏa mãn $C^{6}_{n} + 3C^{7}_{n} + 3C^{8}_{n} +C^{9}_{n} = 2 C^{8}_{n+2}$','$2^5C^{5}_{15}$','$2^6C^{5}_{15}$','$2^5C^{6}_{15}$','$2^6C^{6}_{15}$','D','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH028','Chọn ngẫu nhiên 1 số tự nhiên bé hơn 8, Khi đó: ','Gọi A là biến cố "Số được chọn là số nguyên tố" thì tập hợp các kết quả thuận lợi cho A là {2, 3, 5, 7}','Xác suất số được chọn lớn hơn 2 là $P = \\frac{5}{7}$','Xác suất số được chọn là hợp số là $P = \\frac{3}{7}$','Không gian mẫu là số phần tử của tập hợp {1, 2, 3, 4, 5, 6, 7}','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH029','Một hộp chứ 20 quả cầu giống nhau gồm 12 quả màu đỏ và 8 quả màu xanh. Lấy ngẫu nhiên (đồng thời) 3 quả. Tính xác suất để ít nhất có một quả màu xanh.','$P= 1- \\frac{A^{3}_{12}}{A^{3}_{20}}$','$P= 1- \\frac{C^{3}_{12}}{C^{3}_{20}}$','$P= \\frac{C^{3}_{12}}{C^{3}_{20}}$','$P= \\frac{A^{3}_{12}}{A^{3}_{20}}$','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH030','Đội học sinh giỏi cấp trường môn tiếng Anh trường THPT X theo từng khối là như sau: Khối 10 có 5 học sinh, khối 11 có 5 học sinh và khối 12 có 5 học sinh. Nhà trường cần chọn một đội tuyển gồm 10 học sinh tham gia thi IOE cấp tỉnh. Tính xác suất để đội lập được có học sinh cả 3 khối và nhiều nhất có 2 học sinh lớp 10.','$P = \\frac{450}{3003}$','$P = \\frac{1}{6}$','$P = \\frac{50}{3003}$','$P = \\frac{500}{3003}$','D','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH031','Gọi X là tập hợp các số tự nhiên gồm 6 chữ số đôi một khác nhau được tạo thành từ các chữ số 1, 2, 3, 4, 5, 6, 7, 8, 9. Chọn ngẫu nhiên một số từ tập hợp X. Tính xác suất để số được chọn chỉ có 3 số lẻ.','$P = \\frac{16}{42}$','$P = \\frac{16}{21}$','$P = \\frac{23}{42}$','$P = \\frac{10}{21}$','D','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH032','Cho tập hợp  E = {1; 2; 3; 4; 5; 6} và M là tập hợp gồm tất cả các số gồm hai chữ số phân biệt lập từ E. Lấy ngẫu nhiên một số thuộc M. Tính xác suất để tổng hai chữ số đó lớn hơn 7. ','$P = \\frac{7}{30}$','$P = \\frac{12}{30}$','$P = \\frac{2}{3}$','$P = \\frac{3}{5}$','C','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH033','Nhà trường tổ chức tham quan dã ngoại cho 10 thành viên tiêu biểu của Câu lạc bộ Toán học và 10 thành viên tiêu biểu của Câu lạc bộ tiếng Anh. Trong một trò chơi, ban tổ chức chọn ngẫu nhiên 5 thành viên tham gia trò chơi. Tính xác suất sao cho trong 5 thành viên được chọn , mỗi Câu lạc có ít nhất 1 thành viên.','$P= 1- \\frac{2C^{5}_{10}}{C^{5}_{20}}$','$P= \\frac{2C^{5}_{10}}{C^{5}_{20}}$','$P= \\frac{C^{5}_{10}}{C^{5}_{20}}$','$P= 1 - \\frac{C^{5}_{10}}{C^{5}_{20}}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH034','Trong khai triển nhị thức Newton của biểu thức $(x^3 - x - 2)^2017$ thì tổng các hệ số của $x^{2k+1}$ và k là số nguyên dương :','$2^{2017}$','$\\frac{2^{2017} + 2^{2016}}{2}$','$\\frac{2^{2017} - 2^{2016}}{2}$','$2^{2016}$','A','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH035','Tính tổng $S = 2^2C^{2}_{2010} - 3^2C^{3}_{2010} + 4^2C^{4}_{2010} - ... + 2010^2C^{2010}_{2010}$','$S = 2010$','$S = -C^{1005}_{2010}$','$S = 0$','$S = - 1005$','C','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH036','Tính tổng $S = C^{0}_{2016} + 2C^{1}_{2016} + 3C^{2}_{2016} + 4C^{3}_{2016} + ... + 2017C^{2016}_{2016}$','$S = 2016 . 2^{2015}$','$S = 2018 . 2^{2016}$','$S = 2015 . 2^{2016}$','$S = 2018 . 2^{2015}$','D','tohop','tohop','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH037','Đội văn nghệ của nhà trường 4 học sinh lớp 12A, 3 học sinh lớp 12B và 2 học sinh lớp 12C. Chọn ngẫu nhiên 5 học sinh từ đội văn nghệ để biểu diễn trong lễ bế giảng năm học. Tính xác suất sao cho lớp nào cũng có học sinh được chọn và có ít nhất 2 học sinh lớp 12A.','$P = \\frac{11}{21}$','$P = \\frac{78}{126}$','$P = \\frac{66}{126}$','$P = \\frac{13}{22}$','B','tohop','xs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH038','Trong đợt thi học sinh giỏi của trường THPT, môn Toán có 5 em đạt giải trong đó có 4 nam và 1 nữ, môn Văn có 5 em đạt giải trong đó có 1 nam và 4 nữ, môn Hóa học có 5 em đạt giải trong đó 2 nam và 3 nữ, môn vật lý có 5 em đạt giải trong đó có 3 nam và 2 nữ. Hỏi có bao nhiêu cách chọn mỗi môn một em học sinh để đi dự đại hội thi đua ? Tính xác suất để có cả học sinh nam và nữ để đi dự đại hội? ','$P = \\frac{576}{625}$','$P = \\frac{577}{625}$','$P = \\frac{49}{625}$','$P = \\frac{48}{625}$','B','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH039',' Trong một đợt kiểm tra về vệ sinh an toàn thực phẩm ngành y tế tại chợ X. Ban quản lý chợ lấy ra 15 mẫu thịt lợn trong đó có 4 mẫu ở quầy A, 5 mẫu ở quầy B, 6 mẫu ở quầy C. Mỗi mẫu thịt này có khối lượng như nhau và để trong các hộp kín có kích thước giống hệt nhau. Đoàn kiểm tra lấy ra ngẫu nhiên ba hộp để phân tích, kiểm tra xem trong hợp thịt lợn có chứa hóa chất "Super tạo nạc" (Clenbuterol) hay không. Tính xác suất để 3 hộp lấy ra có đủ 3 loại tịt ở quầy A, B, C.','$P = \\frac{24}{91}$','$P = \\frac{17}{24}$','$P = \\frac{24}{455}$','$P = \\frac{17}{91}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH040','Tìm hệ số số hạng chứ $x^5$ trong khai triển $(1 + 3x)^{2n}$ biết $A^{3}_{n} + 2A^{2}_{n} = 100$.','$ -6^5 C^{5}_{12}$','$ -3^5 C^{5}_{12}$','$ 3^5 C^{5}_{10}$','$ 6^5 C^{5}_{10}$','C','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH041','Một hộp đựng 9 tấm thẻ được đánh số từ 1 đến 9. Hỏi phải rút ít nhất bao nhiêu thẻ để xác suất có ít nhất một thẻ ghi số chia hết cho 4 phải lớn hơn $\\frac{5}{6}$','5 tấm thẻ','6 tấm thẻ','7 tấm thẻ','2 tấm thẻ','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH042','Một hộp đựng chứa 4 viên bi trắng, 5 viên bi đỏ và 6 viên bi xanh. Lấy ngẫu nhiên từ hộp ra 4 viên bi. Tính xác suất để 4 viên bi được chọn có đủ 3 màu và số bi đỏ nhiều nhất','$P = \\frac{5}{11}$','$P = \\frac{19}{91}$','$P = \\frac{16}{91}$','$P = \\frac{17}{91}$','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH043','Trong các phát biểu sau, phát biểu nào đúng ?','Hai biến cố xung khác là hai biến cố đối nhau','Hai biến cố đối lập có ít nhất một trong hai biến cố xảy ra.','Hai biến cố xung khác là hai biến cố cùng xảy ra.','Hai biến cố đối nhau là hai biến cố xung khắc.','D','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH044','Phát biểu nào sai khi nói về "phép thử ngẫu nhiên"?','Có thể xác định được tập hợp kết quả có thể xảy ra của phép thử đó','Kết quả của nó không đoán trước được.','Bao gồm tập hợp các "không gian mẫu" của phép thử','Là một thí nghiệm hoặc một hành động','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH045','Cho 100 tấm thẻ đánh số từ 1 đến 100, chọn ngẫu nhiên 3 thẻ. Tính xác suất để tổng các số ghi trên 3 thẻ được chọn là số chia hết cho 2.','$P = \\frac{5}{6}$','$P = \\frac{1}{2}$','$P = \\frac{5}{7}$','$P = \\frac{3}{4}$','B','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH046','Đoàn trường có 18 chi đoàn học sinh gồm 6 chi đoàn khối 10, 5 chi đoàn khối 11 và 7 chi đoàn khối 12. Nhân kỉ niệm "85 năm thành lập Đoàn thanh niên cộng sản Hồ Chí Minh". Đoàn trường cần chọn 4 bí thư chi đoàn từ các bí thứ trên để đi tham dự mít tinh ở Huyện đoàn. Tính xác suất để chọn được 4 bí thứ chi đoàn sao cho có đủ bí thư chi đoàn của ba khối.','$P = \\frac{68}{72}$','$P = \\frac{35}{72}$','$P = \\frac{35}{68}$','$P = 1- \\frac{35}{72}$','C','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH047','Cho tập hợp  A = {1; 2; 3; 4; 5; 6 ; 7}. Từ các phần tử của tập hợp A lập các số tự nhiên có 4 chữ số, các chữ số đôi một khác nhau, chọn ngẫu nhiên một số từ số mới lập đó. Tính xác suất để số được chọn có chữ số hàng nghìn nhỏ hơn 5.','$P = \\frac{2}{7}$','$P = \\frac{4}{7}$','$P = \\frac{5}{7}$','$P = \\frac{3}{7}$','B','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH048','Gọi S là tập hợp các số tự nhiên gồm 4 chữ số khác nhau được chọn từ các số 0, 1, 2, 3, 4, 5. Chọn ngẫu nhiên một số từ tập S, Tính xác suất để số được chọn có mặt ít nhất chữ số 1 hoặc chữ số 2','$P = \\frac{47}{50}$','$P = \\frac{3}{50}$','$P = \\frac{3}{25}$','$P = \\frac{3}{47}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH049','Có bao nhiêu số tự nhiên có 5 chữ số khác nhau mà trong mỗi số luôn luôn có mặt hai chữ số chẵn và ba chữ số lẻ.','11040 số','12000 số','960 số','13200 số','A','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH050','Quy tắc cộng còn có thể được phát biểu dưới dạng','Nếu A và B là hai tập hợp hữu hạn không hợp nhau thì số phần tử $A \\cup B$ bằng số phần tử của A cộng với số phần tử B','Nếu A và B là hai tập hợp hữu hạn không giao nhau thì số phần tử $A \\cap B$ bằng số phần tử của A cộng với số phần tử B','Nếu A và B là hai tập hợp hữu hạn không giao nhau thì số phần tử $A \\cup B$ bằng số phần tử của A cộng với số phần tử của B','Nếu A và B là hai tập hợp hữu hạn không hợp nhau thì số phần tử $A \\cap B$ bằng số phần tử của A cộng với số phần tử của B','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH051','Tìm hệ số của $x^5$ trong khai triển biểu thức $P = x(1- 2x)^n +x^2(1+3x)^{2n}$ biết rằng $A^{2}_{n} - C^{n - 1}_{n + 1} = 5$','3320','-4802','1549','-3032','A','tohop','newton','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH052','Trong đợt tuyển chọn và gọi công nhân nhập ngũ năm 2016, xã A tuyển chọn được 10 người trong đó có một người tên Hùng và một người tên Dũng. Xã A cần chọn ra từ đó 6 người để thực hiện nghĩa vụ quân sự đợt này. Tính xác suất của biến số 6 người được chọn trong 10 người này không có mặt đồng thời cả Hùng và Dũng.','$P = 1 - \\frac{C^{4}{8}}{C^{6}{10}}$','$P = 1 - \\frac{C^{6}{8}}{C^{6}{10}}$','$P = \\frac{C^{4}{8}}{C^{6}{10}}$','$P = \\frac{C^{6}{8}}{C^{6}{10}}$','A','tohop','xs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH053','Tổ Toán-Tin của một trường gồm 10 giáo viên trong đó có 3 giáo viên nam, 7 giáo viên nữ. Tổ Lý -Hóa- Sinh của trường gồm 12 giáo viên trong đó có 3 giáo viên nam, 9 giáo viên nữ. Chọn ngẫu nhiên mỗi tổ 2 giáo viên đi chuyên đề. Tính xác suất sao cho các giáo viên được chọn có cả nam và nữ.','$P = \\frac{49}{66}$','$P = \\frac{17}{205}$','$P = \\frac{76}{205}$','$P = \\frac{17}{66}$','A','tohop','xs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH054','Trong khai triển nhị thức newton của biểu thức $(a + b)$','Tích số mũ của a và b là hằng số ','Tổng số mũ a và b luôn không đổi','Tổng số mũ của a và b nhỏ nhất khi và chỉ khi hai số mũ bằng nhau','Tích số mũ của a và b lớn nhất khi và chỉ khi hai số mũ bằng nhau ','B','tohop','newton','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH055','Một tổ có 15 học sinh trong đó có 9 học sinh nam và 6 học sinh nữ. Hỏi có bao nhiêu cách chia tổ thành 3 nhóm sao cho mỗi nhóm có đúng 3 học sinh nam và 2 học sinh nữ','$C^{3}{9}C^{2}{6}C^{4}{6}C^{3}{4}$ cách','$C^{3}{9}C^{4}{6}C^{2}{6}C^{2}{4}$ cách','$C^{4}{9}C^{2}{6}C^{4}{6}C^{2}{4}$ cách','$C^{3}{9}C^{2}{6}C^{3}{6}C^{2}{4}$ cách','D','tohop','tohop','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH056','Tìm số nguyên dương $n$ thỏa mãn $ A^{2}_{n} - 3C^{2}_{n} = 15 - 5n$','n = 5 hoặc n = 6 hoặc n = 12 ','n = 5 hoặc n = 6','n = 6','n =5','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH057','Tìm hệ số chứa x^2 trong khai triển nhị thứ Newton $\\left( x^2 + \\frac{2}{x} \\right)^n biết n là số nguyên dương tỏa mãn $3C^{3}_{n+1} - 3A^{2}_{n} = 52(n-1)$','$2^8 C^{8}_{13}$','$2^7 C^{7}_{13}$','$2^5 C^{5}_{13}$','$2^6 C^{6}_{13}$','A','tohop','tohop','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH058','Từ các số tự nhiên 1, 2, 3, 4 có thể lập được bao nhiêu số tự nhiên có 4 chữ số khác nhau?','$4^4$','24','1','42','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH059','Từ các số tự nhiên 1, 2, 3, 4 có thể lập được bao nhiêu số tự nhiên có 3 chữ số khác nhau?','12','6','4','24','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH060','Từ các số tự nhiên 1, 2, 3, 4, 5, 6 có thể lập được bao nhiêu số tự nhiên có 5 chữ số?','120','1','3125','600','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH061','Cho $A = {1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số chẵn có 5 chữ số ?','3888','360','15','120','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH062','Cho $A = {0, 1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số tự nhiên có 5 chữ số đôi một khác nhau ','2160','2520','21','5040','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH063','Cho $A = {0, 1, 2, 3, 4, 5, 6}$. Từ A có thể lập được bao nhiêu số lẻ có 5 chữ số đôi một khác nhau ','2520','900','1080','21','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH064','Từ các số 0, 1, 2, 3, 4, 5, 6 có thể lập được bao nhiêu số tự nhiên có 3 chữ số ','210','105','168','84','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH065','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong lớp','9880','59280','2300','455','A','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH066','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong đó có 1 học sinh nam và 2 học sinh nữ','5250','4500','2625','1500','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH067','Một lớp học có 40 học sinh gồm 25 nam và 15 nữ. Chọn 3 học sinh tham gia vệ sinh công cộng toàn trường, hỏi có bao nhiêu cách chọn 3 học sinh trong đó có nhiều nhất 1 học sinh nam.','2625','455','2300','3080','D','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH068','Một nhóm học sinh có 4 nam và 3 nữ Có bao nhiêu cách chọn 3 bạn trong đó có đúng 1 bạn nữ?','8','18','28','38','B','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH069','Một nhóm học sinh có 6 bạn nam và 5 bạn nữ có bao nhiêu cách chọn ra 5 bạn trong đó có 3 bạn nam và 2 bạn nữ','462','2400','200','20','C','tohop','tohop','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('TH070','Một hộp đựng 5 viên bi màu xanh, 7 viên bi màu vàng. Có bao nhiêu các lấy ra 6 viên bi bất kỳ?','665280','924','7','942','B','tohop','tohop','0',NULL,'11','0');

/* Phep doi hinh */


/* Day so */
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS001','Cho dãy số $(u_n)$ với $u_n = \\frac{-n}{n+1}$ Khẳng định nào sau đây là đúng?','5 số hạng đầu của dãy là: $\\frac{-1}{2};frac{-2}{3};frac{-3}{4};frac{-5}{5};frac{-5}{6};$','5 số hạng đầu của dãy là: $\\frac{-1}{2};frac{-2}{3};frac{-3}{4};frac{-4}{5};frac{-5}{6};$','Là dãy số tăng','Bị chặn trên bởi 1','B','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS002','Cho dãy số $(u_n)$ với $u_n = \\frac{1}{n^2+n}$ Khẳng định nào sau đây là sai?','5 số hạng đầu của dãy là: $\\frac{1}{2};frac{1}{6};frac{1}{12};frac{1}{20};frac{1}{30};$','Là dẫy số giảm','Bị chặn trên bởi $M = \\frac{1}{2}$','Không bị chặn','C','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS003','Cho dãy số $(u_n)$ với $u_n = \\frac{-1}{n}$ Khẳng định nào sau đây là sai?','5 số hạng đầu của dãy là: $-1; \\frac{-1}{2};frac{-1}{3};frac{-1}{4};frac{-1}{5};$','Bị chặn trên bởi $M = -1$','Bị chặn trên bởi $M = 0$','Là dãy số giảm và bị chặn dưới bởi số m = -1','B','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS004','Cho dãy số $(u_n)$ với $u_n =a. 3^n$ (a: hằng số). Khẳng định nào dưới đây là sai?','Dãy số có $u_{n+1} = a. 3^{n+1}$','Hiệu số $u_{n+1} - u_n = 3a$','Với a > 0 thì dãy số tăng','Với a < 0 thì dãy số giảm','B','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS005','Cho dãy số $(u_n)$ với $u_n = \\frac{a-1}{n^2}$ Khẳng định nào sau đây là đúng?','Dãy số có $u_{n+1} = \\frac{a-1}{n^2+1}$','Dãy số có $u_{n+1} = \\frac{a-1}{(n+1)^2}$','Là dãy số giảm','Là dãy số tăng','B','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS006','Cho dãy số $(u_n)$ với $u_n = \\frac{a-1}{n^2}$ (a: hằng số) Khẳng định nào sau đây là sai?','$u_{n+1} = \\frac{a-1}{(n+1)^2}$','Hiệu số $u_{n+1} - u_n = (1 - a) \\frac{2n+1}{(n+1)^2.n^2$','Hiệu số $u_{n+1} - u_n = (a - 1) \\frac{2n+1}{(n+1)^2.n^2$','Dãy số tăng khi a < 1','C','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS007','Cho dãy số $(u_n)$ với $u_n = \\frac{an^2}{n + 1}$ (a: hằng số) $u_{n+1}$ là số hạng nào sau đây?','$u_{n+1} = \\frac{a.(n + 1)^2}{n+2}$','$u_{n+1} = \\frac{a.(n + 1)^2}{n+1}$','$u_{n+1} = \\frac{a.n^2 + 1}{n+1}$','$u_{n+1} = \\frac{a.n^2}{n+1}$','A','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS008','Cho dãy số $(u_n)$ với $(u_n) = \\frac{an^2}{n+1}$ ( a:hằng số). Phát biểu nào sau đây là sai?','$u_{n+1} = \\frac{a.(n+1)^2}{n+2}$','$u_{n+1} - u_n = \\frac{a.(n^2+3n+1)^2}{(n+2)(a+1)}$','Là dãy số luôn tăng với mọi a','Là dãy số tăng với $a > 0$','C','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS009','Cho dãy số với các số hạn đầu là ( bắt đầu từ n = 1): 5, 5*2, 5*3, 5*4, 5*5, .... Số hạng tổng quát là ','$u_n = 5(n+1)$','$u_n = 5n$','$u_n = 5^n$','$u_n = 5n+1$','B','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS010','Cho dãy số có các số hạng đầu là: 8, 15, 22, 29, 36, .... Số hạng tổng quát là ','$u_n = 7n + 7$','$u_n = 7n$','$u_n = 7n + 1$','$u_n$: không viết được dưới dạng công thức','C','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS011','Cho dãy số có các số hạng đầu là: $0, \\frac{1}{2}, \\frac{2}{3}, \\frac{3}{4}, \\frac{4}{5}, .... Số hạng tổng quát là ','$u_n = \\frac{n + 1}{n}$','$u_n = \\frac{n}{n + 1}$','$u_n = \\frac{n - 1}{n}$','$u_n = \\frac{n * n }{2}$','C','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS012','Cho dãy số có các số hạng đầu là: 0,1;0,01;0,001;0,0001; .... Số hạng tổng quát có dạng','$u_n = 0,000 ..01$ có n chữ số 0 ','$u_n = 0,000 ..01$ có n - 1 chữ số 0 ','$ u_n = \\frac{1}{10^{n-1}}$','$ u_n = \\frac{1}{10^{n+1}}$','B','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS013','Cho dãy số có các số hạng đầu là: -1, 1, -1, 1, -1,.... Số hạng tổng quát là ','$u_n = 1$','$u_n = -1$','$u_n = (-1)^n$','$u_n = (-1)^{n+1}$','C','dayso','dayso ','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS014','Cho dãy số có các số hạng đầu là: $0, \\frac{1}{3}, \\frac{1}{3^2}, \\frac{1}{3^3}, \\frac{1}{3^4}, .... Số hạng tổng quát là ','$u_n = \\frac{1}{3}\\frac{1}{3^{n+1}}$','$u_n = \\frac{1}{3^{n+1}}$','$u_n = \\frac{1}{3^n}$','$u_n = \\frac{1}{3^{n-1}}$','C','dayso','dayso','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS015','Cho dãy số $(u_n)$ với $(u_n) = \\frac{k}{3^n}$ ( k:hằng số). Phát biểu nào sau đây là sai?','Số hạng thứ 5 của dãy: $ \\frac{k}{3^5}$','Số hạng thứ n của dãy: $ \\frac{k}{3^{n+1}}$','Là dãy số giảm khi k > 0','Là dãy số tăng khi k > 0','D','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS016','Cho dãy số có các số hạng đầu là: -2, 0, 2, 4, 6,.... Số hạng tổng quát là ','$u_n = -2n$','$u_n = -2 + n$','$u_n = -2(n + 1)$','$u_n = -2 + 2(n - 1)$','D','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS017','Cho dãy số $(u_n)$ với $(u_n) = \\frac{1^{n+1}}{n+1}$  Phát biểu nào sau đây là sai?','Số hạng thứ 9 của dãy: $\\frac{1}{10}$','Số hạng thứ 10 của dãy: $\\frac{1}{11}$','Đây là một dãy số giảm','Bị chặn trên bởi M = 1','C','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS018','Cho dãy số $(u_n)$ với $(u_n) = \\sqrt{n-1}$ với $n \\in \\mathbb{N}*$. Khẳng định nào sau đây là sai?','5 số hạng đầu của dãy là $0, 1, \\sqrt{2}, \\sqrt{3}, \\sqrt{5}$','Số hạng $u_{n+1} = \\sqrt{n}$','Là dãy số tăng','Bị chặn dưới bởi số 0','A','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS019','Cho dãy số $(u_n)$ có $u_n= - n^2 +n +1$ Khẳng định nào sau đây là đúng?','5 số hạng đầu của dãy là 1,1,-5,-11,-19','Số hạng $u_{n+1} = -n^2 + n +2$','Hiệu số $u_{n+1} - u_n = 1$','Là dãy số giảm ','D','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS020','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = -2  \\\\ u_{n+1} = -2 - \\frac{1}{u_n} \\end{array} \\right.$ Khẳng định nào sau đây là đúng?','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{-n+1}{n}$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{n+1}{n}$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{-(n+1)}{n}$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{-n}{n+1}$','C','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS021','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 5  \\\\ u_{n+1} = u_n +n  \\end{array} \\right.$Số hạng tổng quát $u_n$ của dãy số là biểu thức nào dưới đây?','$u_n = \\frac{(n-1)n}{2}$','$u_n =5 + \\frac{(n-1)n}{2}$','$u_n =5 + \\frac{n(n+1)}{2}$','$u_n =5 + \\frac{5(n+1)(n+2)}{2}$','B','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS022','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 1\\\\ u_{n+1} = u_n +(-1)^{2n}  \\end{array} \\right.$Số hạng tổng quát $u_n$ của dãy số là biểu thức nào dưới đây?','$u_n = 1 +n$','$u_n = 1 - n$','$u_n = 1 + (-1)^{2n}$','$u_n = n$','D','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS023','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 1\\\\ u_{n+1} = u_n +(-1)^{2n+1}  \\end{array} \\right.$Số hạng tổng quát $u_n$ của dãy số là biểu thức nào dưới đây?','$u_n = 2 - n$','$u_n$ không xác định ','$u_n = 1 - n$','$u_n = - n$ với mọi n ','A','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS024','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 1\\\\ u_{n+1} = u_n + n^2\\end{array} \\right.$Số hạng tổng quát $u_n$ của dãy số là biểu thức nào dưới đây?','$u_n = 1 + \\frac{n(n+1)(2n+1)}{6}$','$u_n = 1 + \\frac{n(n-1)(2n+2)}{6}$','$u_n = 1 + \\frac{n(n-1)(2n-1)}{6}$','Một kết quả khác','C','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS025','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 2\\\\ u_{n+1} - u_n = 2n - 1\\end{array} \\right.$Số hạng tổng quát $u_n$ của dãy số là biểu thức nào dưới đây?','$u_n = 2 + (n-1)^2$','$u_n = 2 + n^2$','$u_n = 2 + (n + 1)^2$','Một kết quả khác','D','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS026','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = \\frac{1}{2} \\\\ u_{n+1} = u_n - 2 \\end{array} \\right.$Khẳng định nào sau đây là đúng ?','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{1}{2} +2(n-1)$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{1}{2} - 2(n-1)$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{1}{2} - 2n$','Công thức số hạng tổng quát của dãy số này: $u_n = \\frac{1}{2} + 2n$','B','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS027','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = -1 \\\\ u_{n+1} = \\frac{u_n}{2} \\end{array} \\right.$Khẳng định nào sau đây là đúng ?','Công thức số hạng tổng quát của dãy số này: $u_n = (-1)\\left(\\frac{1}{2}\\right)^n$','Công thức số hạng tổng quát của dãy số này: $u_n = (-1)\\left(\\frac{1}{2}\\right)^{n+1}$','Công thức số hạng tổng quát của dãy số này: $u_n = \\left(\\frac{1}{2}\\right)^{n - 1}$','Công thức số hạng tổng quát của dãy số này: $u_n = (-1)\\left(\\frac{1}{2}\\right)^{n - 1}$','D','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS028','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 = 2 \\\\ u_{n+1} = 2 u_n \\end{array} \\right.$Khẳng định nào sau đây là đúng ?','Công thức số hạng tổng quát của dãy số này: $u_n = n^{n-1}$','Công thức số hạng tổng quát của dãy số này: $u_n = 2^n$','Công thức số hạng tổng quát của dãy số này: $u_n = 2^{n+1}$','Công thức số hạng tổng quát của dãy số này: $u_n = 2$','B','dayso','dayso','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS029','Cho dãy số $(u_n)$ với $\\left\\{\\begin{array} {1}u_1 =\\frac{1}{2} \\\\ u_{n+1} = 2 u_n \\end{array} \\right.$Khẳng định nào sau đây là đúng ?','Công thức số hạng tổng quát của dãy số này: $u_n = -2^{n-1}$','Công thức số hạng tổng quát của dãy số này: $u_n = -\\frac{1}{2^{n-1}}$','Công thức số hạng tổng quát của dãy số này: $u_n = -\\frac{1}{2^n}$','Công thức số hạng tổng quát của dãy số này: $u_n = -2^{n-2}$','D','dayso','dayso ','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS030','Cho dãy số $(u_n)$ với $u_n = -\\frac{1}{n^2+1}$Khẳng định nào sau đây là sai?','$u_{n+1} = \\frac{-1}{(n+1)^2+1}$','$u_n > u_{n+1}$','Đây là một dãy số tăng','Bị chặn dưới bởi số 0','B','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS031','Cho dãy số $(u_n)$ với $u_n = sin \\frac{\\pi}{n}$Khẳng định nào sau đây là sai?','Số hạng thứ n+1 của dãy: $u_{n+1} = sin \\frac{\\pi}{n + 1}$','Dãy số bị chặn','Là dãy số tăng','Không tăng không giảm','C','dayso','dayso','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS032','Khẳng định nào sau đây là sai?','Dãy số: $-\\frac{1}{2},0,\\frac{1}{2},1,\\frac{3}{2},...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =\\frac{1}{2} \\\\ d =\\frac{1}{2} \\end{array} \\right.$','Dãy số: $\\frac{1}{2},\\frac{1}{2^2},\\frac{1}{2^3},...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =\\frac{1}{2} \\\\ d =\\frac{1}{2} n=3 \\end{array} \\right.$','Dãy số: $ -2, -2, -2, -2,...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =2 \\\\ d =0 \\end{array} \\right.$','Dãy số: $ 0,1;0,01;0,001;0,0001;....$ không phải là cấp số cộng.','B','dayso','csc','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS033','Khẳng định nào sau đây là sai?','Dãy số: $1, \\frac{1}{2},\\frac{1}{3},\\frac{1}{4},\\frac{1}{5}...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =1 \\\\ d =\\frac{1}{n(n+1)} \\end{array} \\right.$','Dãy số: $\\frac{1}{2},\\frac{1}{2^2},\\frac{1}{2^3},...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =\\frac{1}{2} \\\\ d =\\frac{1}{2} n=3 \\end{array} \\right.$','Dãy số: $1,0, -1,-2,-1,...$ là cấp số cộng $\\left\\{\\begin{array} {1}u_1 =1 \\\\ d = -1 \\\\n=4 \\end{array} \\right.$','Dãy số 3, 9, 27, 81, ... Không phải là cấp số cộng','A','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS034','Cho cấp số cộng có $u_1 = -\\frac{1}{2}; d=-\\frac{1}{2}$ Chọn kết quả đúng','Dạng khai triển: $-\\frac{1}{2}, 0, 1,\\frac{1}{2},1,....$','Dạng khai triển: $-\\frac{1}{2}, 0, \\frac{1}{2}, 0, \\frac{1}{2},....$','Dạng khai triển: $\\frac{1}{2}, 1, \\frac{3}{2}, 2, \\frac{5}{2},....$','Dạng khai triển: $\\frac{-1}{2}, 0, \\frac{1}{2}, 1, \\frac{3}{2},....$','D','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS035','Cho cấp số cộng có $u_1 = -3; u_6= 27$ Tìm d','$d = 5$','$d = 7$','$d = 6$','$d = 8$','C','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS036','Cho cấp số cộng có $u_1 = -\\frac{1}{3}; u_8= 26$ Tìm d','$d = \\frac{11}{3}$','$d = \\frac{3}{11}$','$d = \\frac{10}{3}$','Một kết quả khác','A','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS037','Cho cấp số cộng có $u_1 = -0.1; d =0.1$ Khẳng định nào sau đây là đúng ?','$u_7 =1.6$','$u_7 =6$','$u_7 = 0.5$','$u_7 =0.6$','C','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS038','Cho cấp số cộng $(u_n)$ có :$u_1 = 0,3; u_8= 8$ Khẳng định nào sau đây là sai ?','Số hạn thứ 2 của cấp số cộng này là 1,4','Số hạn thứ 3 của cấp số cộng này là 2,5','Số hạn thứ 4 của cấp số cộng này là 3,6','Số hạn thứ 7 của cấp số cộng này là 7,7','D','dayso','csc','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS039','Viết 3 số xen giữa các số 2 và 22 để được cấp số cộng có 5 số hạng','42928','41800','43325','Một kết quả khác','A','dayso','csc','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS040','Viết 4 số hạng xen giữ $\\frac{1}{3}$ và $\\frac{16}{3}$ để được cấp số cộng có 6 số hạng.','$\\frac{4}{3},\\frac{5}{3},\\frac{6}{3},\\frac{7}{3}$','$\\frac{4}{3},\\frac{7}{3},\\frac{11}{3},\\frac{14}{3}$','$\\frac{4}{3},\\frac{7}{3},\\frac{10}{3},\\frac{13}{3}$','$\\frac{3}{4},\\frac{7}{4},\\frac{11}{4},\\frac{15}{4}$','C','dayso','csc','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS041','Cho dãy số $(u_n)$ với: $u_n = 7-2n$. Khẳng định nào sau đây là sai?','3 số hạng đầu của dãy: $u_1 = 5,u_2 = 3,u_3 = 1$','Số hạng thức $n +1 :u_{n+1} = 8-2n$','Là cấp số cộng có d= -2',' Số hạng thứ 4  là -1','B','dayso','csc','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS042','Cho csc có $u_1 = \\sqrt{2}; d=\\sqrt{2}; s= 8\\sqrt{2}$ Khẳng định nào sau đây là đúng?','S là tổng của 5 số hạng đầu của cấp số cộng','S là tổng của 6 số hạng đầu của cấp số cộng','S là tổng của 7 số hạng đầu của cấp số cộng','Một kết quả khác','D','dayso','csc','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS043','Công thức nào sau đây đúng với cấp số cộng có số hạng đầu $u_1$, công sai d?','$u_n =u_n+d$','$u_n =u_1 + (n + 1)d$','$u_n =u_n - (n-1)d$','$u_n =u_n + (n-1)d$','D','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS044','Cho csc có $u_1 = \\sqrt{2}; d=-\\sqrt{2}; s= 8\\sqrt{2}$ Khẳng định nào sau đây là đúng?','S là tổng của 2 số hạng đầu của cấp số cộng','S là tổng của 3 số hạng đầu của cấp số cộng','S là tổng của 4 số hạng đầu của cấp số cộng','S không là tổng của các số hạng đầu của cấp số','D','dayso','csc','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS045','Xác định x để 3 số : $1- x,x^2,1+x $ lập thành cấp số cộng','Không tồn tại X','$x= 2$ hoặc $x =-2$','$x =1$ hoặc $x = -1$','$ x =0 $','C','dayso','csc','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS046','Cho a,b,c lập thành cấp số cộng, 3 số nào dưới đây cũng thành lập cấp số cộng','$2b^2, a^2, c^2$','$-2b, -2b, -2c$','$2b, a ,c$','$2b, -a , -c$','B','dayso','csc','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS047','Cho cấp số cộng: -2, -5, -8, -11, -14,... Tìm d và tổng số hạng 20 số đầu tiên.','$d = 3; S_{20} =510$','$d = -3; S_{20} = -610$','$d = -3; S_{20} = 610$','Một kết quả khác','B','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS048','Cho dãy số -1, 1, -1, 1, -1,... Khẳng định nào sau đây là đúng?','Dãy số này không phải là cấp số nhân','số hạng tổng quát là $U_n =1^n =1$','Dãy số này là cấp số nhân có $U_1 = -1, q=-1$','Số hạng tổng quát $U_n = (-1)^{2n}$','C','dayso','csn','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS049','Cho dãy số -1, -1, -1, -1, -1,... Khẳng định nào sau đây là đúng?','Dãy số này không phải là cấp số nhân','Dãy số này là cấp số nhân có $U_1 = -1, q=1$','Số hạng tổng quát $U_n = (-1)^{n}$','Là dãy số giảm','B','dayso','csn','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS050','Cho cấp số nhân có $u_2 =\\frac{1}{4}; u_5 =16.$ Tìm q và $u_1$','$q =\\frac{1}{2} ; u_1 =\\frac{1}{2}$','$q = -\\frac{1}{2} ; u_1 =-\\frac{1}{2}$','$q = 4; u_1 =\\frac{1}{16}$','$q = -4; u_1 = -\\frac{1}{16}$','C','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS051','Cho cấp số nhân có $u_1 = -3; q = \\frac{2}{3}, \\frac{96}{243}$ là số hạng thứ mấy của cấp số nhân.','5','6','7','Không phải','B','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS052','Chọn cấp số nhân trong các dãy số sau ','1; 0.2; 0,04; 0,0008; ....','2; 22; 222; 2222;...','x;2x;3x;4x','$1; -x^2;x^4$;-x^6$','D','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS053','Cho dãy số $(U_n) : x, -x^3, x^5, -x^7,...$ (với $x \\in \\mathbb{R},x <> 0 $ Chọn mệnh đề sai.','Là dãy số không tăng không giảm ','Là cấp số nhân có $U_n = (-1)^{n-1}+x^{2n-1}$','Có tổng $S_n = \\frac{x(1-x^{2n-1}}{1-x^2}$','Là cấp số nhân có $u_1 =x ,q =-x^2$','C','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS054','Cho cấp số nhân $(U_n) với $U_1 = 3 ; q= -\\frac{1}{2}$. Số 222 là số hạng thứ mấy?','Số hạng thứ 11','Số hạng thứ 12','Không phải','Số hạng thứ 9','C','dayso','csn','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS055','Cho cấp số nhân $(U_n) với $U_1 = 3 ; q= -2$. Số 192 là số hạng thứ mấy?','Số hạng thứ 5','Số hạng thứ 6','Số hạng thứ 7','Không phải','C','dayso','csn','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS056','Cho cấp số nhân $(U_n) với $U_1 = -1 ; q= \\frac{1}{10}$. Số $\\frac{1}{10^{103}} là số hạng thứ mấy?','103','104','102','Không phải ','B','dayso','csn','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS057','Cho cấp số nhân $(U_n) với $U_1 = 3 ; U_6= 0.00001$. Tính q và $U_n$','$q=\\frac{1}{10}, U_n = \\frac{-1}{10^{n-1}}$','$q=\\frac{1}{10}, U_n = -10^{n-1}$','$q=\\frac{-1}{10}, U_n = \\frac{1}{10^{n-1}}$','$q=\\frac{-1}{10}, U_n = \\frac{(-1)^n}{10^{n-1}}$','D','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS058','$a,b,c,d,e$ là 5 số hạng liên tiếp của cns. Biết $ace =125$ thì có giá trị là','15','5','25','10','C','dayso','csc','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS059','Một người muốn chia 1 triệu đồng cho bốn người con, đứa lớn hơn đứa nhỏ kế tiếp 100.000 đồng. Hỏi đứa lớn tuổi nhất được bao nhiêu ?','100.000 đồng','300.000 đồng','400.000 đồng','200.000 đồng','C','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS060','Một du khách vào chuồng ngựa đặt cược, lần đầu đặt 20.000 đồng, mỗi lần sau đặt tiền gấp đôi lần trước. Người đó thua 9 lần liên tiếp và thắng ở lần thứ 10. Hỏi du khách trên được hay mất bao nhiêu tiền ?','hòa','thua 20.000 đồng','thắng 20.000 đồng','thua 40.000 đồng','C','dayso','csn','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS061','Cho tam giác ABC biết 3 góc của tam giác lập thành một cấp số cộng và có một góc bằng $25^o$ tính đo các gốc :','$25^o, 65^o, 90^o$','$25^o, 75^o, 80^o$','$25^o, 60^o, 95^o$','$25^o, 60^o, 90^o$','C','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS062','Cho a,b,c lập thành cấp số cộng, đẳng thức nào sau đây là đúng ?','$a^2 + c^2 =2ab + 2bc$','$a^2 - c^2 =2ab - 2bc$','$a^2 + c^2 =2ab - 2bc$','$a^2 - c^2 = ab - bc$','B','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS063','Cho tứ giác ABCD biết 4 góc của tam giác lập thành một cấp số cộng và có một góc bằng $30^o$ tính đo các gốc :','$30^o 75^o 120^o 165^o$','$30^o 72^o 114^o 156^o$','$30^o 70^o 110^o 150^o$','Một kết quả khác','C','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS064','Cho dãy số: $\\frac{1}{2}, \\frac{1}{2}, \\frac{3}{2}, \\frac{5}{2}$,... Khẳng định nào sau đây là sai?','Là một cấp số cộng ','có d =-1','số hạng thứ 20: $U_{20} = 19.5$','Tổng số hạng 20 số dầu tiên là $-180$','C','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS065','Công thức tính tổng n số hạng đầu của cấp số cộng là','$S_n = \\frac{n(2u_1+(n-1)d}{2}$','$S_n = \\frac{n(2u_1+(n+1)d}{2}$','$S_n = \\frac{n(2u_1+n d}{2}$','$S_n = \\frac{n(2u_1+(n-2)d}{2}$','A','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS066','Một cấp số cộng có $u_3 + u_5 = 5 Và $u_3 * u_5 = 6$. Giá trị $u_1$ là:','2','4','3','-4','B','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS067','Một cấp số cộng có $u_1 = 5 ,$u_{12} = 38. Giá trị $u_{10}$ là:','24','32','30','35','B','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS068','Cho cấp số cộng $(u_n)$ có :$u_5 = 18; 4S_n = S_{2n}$. Giá trị $u_1$ và d là:','$u_1 = 3;d=2$','$u_1 = 2;d = 2$','$u_1 = 2;d = 4$','$u_1 = 2;d = 3$','C','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS069','Cho cấp số cộng có 4 số hạng trong đó tổng của chúng bằng 22, tổng bình phương bằng 166, 4 số hạng của cấp số cộng là:','1; 4; 7; 10','1; 4; 5; 10','2; 3; 5; 10','2; 3; 4; 5','A','dayso','csc','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('DS070','Cho cấp số cộng $(u_n)$ có $u_1 = -1, d=2, S_n = 483$. Số các số hạng của cấp số cộng đó là:','20','21','22','23','B','dayso','csc','0',NULL,'11','0');

/* Gioi han */
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH001','Cho dãy số $(u_n)$ với $u_n  = \\frac{1}{2n}$: chọn số dương $M = \\frac{1}{100}$ để $\\frac{1}{2n} < \\frac{1}{100}$ thì phải kể từ số hạng thứ bao nhiêu trở đi ?','51','49','18','50','A','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH002','Cho dãy số $(u_n)$ với $u_n  = \\frac{1}{2n + 1}$: chọn số dương $M = \\frac{1}{1000}$ để $\\frac{1}{2n + 1} < \\frac{1}{1000}$ thì phải kể từ số hạng thứ bao nhiêu trở đi ?','thứ 498','thứ 499','thứ 500','thứ 501','C','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH003','Cho dãy số $(u_n)$ với $u_n = \\frac{1}{2^n}$. Chọn số dương $M = \\frac{1}{2^{10}}$ để $\\frac{1}{2^n} < \\frac{1}{2^{10}}$. Thì phải kể từ số hạng thứ bao nhiêu trở đi?','thứ $2^{10} -1$','thứ $2^{10}$','thứ $2^{10} + 1$','thứ $\\frac{1}{2^{10}} + 1$','C','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH004','Cho dãy số $(u_n)$ với $u_n = 2^n$. Cho $M = \\frac{1}{2^{10}}$ để $ 2^n < \\frac{1}{2^{10}}$ thì phải kể từ số hạng thứ mấy trở đi?','Không có số hạng nào thỏa mãn ','thứ $\\frac{1}{2^10 + 1}$','thứ $\\frac{1}{2^10} + 1$','thứ $2^10$ +1','A','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH005','Chọn mệnh đề đúng dưới đây','$lim 10^{-n} \\neq 0$','$lim \\left( \\frac{4}{3} \\right)^n = 0$','$lim \\left( \\frac{3}{4} \\right)^n = lim \\left( \\frac{2}{3} \\right)^n =  0$','$lim \\left( \\frac{3}{2} \\right)^n = 0$','C','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH006','Chọn kết quả đúng : $lim \\frac{1 +\\sqrt{n}}{n}$ bằng','1','0','2','$+\\infty$','B','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH007','Chọn kết quả đúng : $lim \\frac{1 + n}{\\sqrt{n}}$ bằng','1','0','2','$+\\infty$','D','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH008','Chọn kết quả đúng : $lim \\frac{3^n +2^n}{4^n}$ bằng','0','$\\frac{5}{4}$','$+\\infty$','$\\frac{3}{4}$','A','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH009','Chọn kết quả đúng : $lim \\frac{n^2 +2n -3 }{ n^2}$ bằng','1','$-\\infty$','-1','0','C','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH010','Chọn kết quả đúng trong các kết quả sau $lim \\frac{\\frac{1}{3}\\sqrt{n} +2n}{3n}$ bằng','$-\\frac{1}{9}$','$\\frac{2}{3}$','$-\\infty$','Một kết quả khác','B','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH011','Chọn kết quả đúng trong các kết quả sau $lim \\frac{1-3n^2}{4-n^2}$ bằng','-3','$\\frac{1}{4}$','$- \\frac{1}{4}$','3','D','gioihan','ghds','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH012','Chọn kết quả đúng trong các kết quả sau $lim (\\sqrt{n} - \\sqrt{n+1})$ bằng','Không có giới hạn khi $n \\rightarrow + \\infty$','-1','0','Một kết quả khác','C','gioihan','ghds','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH013','Chọn mệnh đề đúng dưới đây','$lim sin\\frac{\\pi}{n}=1$','$lim sin\\frac{\\pi}{n}= - 1$','$lim sin\\frac{\\pi}{n}=0$','Không có giới hạn khi $n \\rightarrow + \\infty$','C','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH014','Chọn mệnh đề đúng dưới đây','$lim \\frac{sin\\frac{\\pi}{n}}{n} =1$ Không có giới hạn khi $n \\rightarrow + \\infty$','$lim \\frac{sin\\frac{\\pi}{n}}{n} = -1$','$lim \\frac{sin\\frac{\\pi}{n}}{n} = 0$','Cả ba kết quả trên đều sai ','C','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH015','Chọn mệnh đề đúng dưới đây','$lim(\\frac{1}{3^n}) - lim(\\frac{1}{4^n}) = frac{1}{12}$ ','$lim \\left[ \\left(\\frac{7}{3}\\right)^n +sin\\frac{1}{n} \\right] = + \\infty$','$lim \\left[ \\left(\\frac{3}{7}\\right)^n + 3^n \\right] = + \\infty$','Cả ba kết quả trên đều sai ','B','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH016','Chọn mệnh đề đúng dưới đây','$lim \\sqrt{\\frac{3n-5}{n^n}} = 0$','$lim \\sqrt{\\frac{3n-5}{n^n}} = 3$','$lim \\sqrt{\\frac{3n-5}{n^n}} = +\\infty$','$lim \\sqrt{\\frac{3n-5}{n^n}} = \\sqrt{3}$','A','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH017','Chọn kết quả đúng dưới đây ','$lim \\sqrt{\\frac{2n-7}{n}} = +\\infty$','$lim \\sqrt{\\frac{2}{n}} = \\sqrt{2}$','$lim \\sqrt{\\frac{2n^2}{n+1}} = \\sqrt{2}$','$lim \\sqrt{\\frac{n-7}{2n}} = \\frac{\\sqrt{2}}{2}$','D','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH018','Chọn mệnh đề đúng dưới đây ','$lim cos\\frac{\\2pi}{n} = 0$','$lim cos\\frac{\\2pi}{n} = 1$','$lim cos\\frac{\\2pi}{n} = -1$','$lim cos\\frac{\\2pi}{n} $ không có kết quả khi $n \\rightarrow +\\infty$','B','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH019','Chọn mệnh đề đúng dưới đây ','$lim n^2 cos\\frac{\\2pi}{n} = +\\infty$','$lim \\frac{cos\\frac{\\pi}{n}}{n^2} = +\\infty$','$lim \\frac{cos\\frac{\\pi}{n}}{n^2 +2} = \\frac{1}{2}$','Cả ba kết quả trên đều sai ','A','gioihan','ghds','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH020','$lim \\sqrt{ \\frac{7 - 2n}{4n + 5}} bằng','$\\sqrt{\\frac{1}{2}}$','$-\\infty$','Không có giới hạn khi $n \\rightarrow + \\infty$','0','C','gioihan','ghds','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH021','Cho hàm số $f(x) = \\frac{ x+1}{x -1}$. Chọn dãy số nào trong các dãy số sau để có $\\lim_{n\\to +\\infty}f(x_n) = -1$ với $x_n \\to n$','Dãy số $(x_n): x_n = \\left( \\frac{5}{4} \\right)^n$','Dãy số $(x_n): x_n = \\left( \\frac{1}{2} \\right)^n$','Dãy số $(x_n): x_n = 2^n$','Dãy số $(x_n): x_n = n$','B','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH022','Cho hàm số $f(x) = \\frac{ -2x}{x +1}$. Chọn dãy số nào trong các dãy số sau để có $\\lim_{n\\to +\\infty}f(x_n) = -1$ với $x_n \\to 1$','Dãy số $(x_n): x_n = \\frac{1}{n}$','Dãy số $(x_n): x_n = n$','Dãy số $(x_n): x_n = -n$','Dãy số $(x_n): x_n = -2n$','A','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH023','Cho hàm số $f(x) = \\sqrt{x+5}$. Cho dãy số nào trong các dãy số sau để có với  $\\lim_{n\\to +\\infty}f(x_n) = +\\infty$ với $x_n \\to +\\infty$','Dãy số $(x_n); x_n =\\frac{1}{n}$','Dãy số $(x_n); x_n = n$','Dãy số $(x_n); x_n = -n$','Dãy số $(x_n); x_n = 5$','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH024','Cho hàm số $f(x) = \\sqrt{x+5}$. Cho dãy số nào trong các dãy số sau để có với  $\\lim_{n\\to +\\infty}f(x_n) = $ không tồn tại giới hạn với $x_n \\to +\\infty$','Dãy số $(x_n); x_n = -n$','Dãy số $(x_n); x_n =\\frac{1}{n}$','Dãy số $(x_n); x_n = n$','Dãy số $(x_n); x_n = -2n$','C','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH025','Chọn kết quả đúng dưới đây ',' $\\lim_{x\\to 1}\\frac{x+1}{x-1} = 1$',' $\\lim_{x\\to 1}\\frac{x+1}{x-1} = 0$',' $\\lim_{x\\to 2}\\frac{x+1}{x-1} = -3$',' $\\lim_{x\\to -2}\\frac{x+1}{x-1} = -\\frac{1}{3}$','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH026','Chọn kết quả đúng dưới đây ',' $\\lim_{x\\to \\frac{1}{2}} \\sqrt{2x-1} = \\sqrt{2}$',' $\\lim_{x\\to \\frac{1}{2}} \\sqrt{2x-1} = 0$',' $\\lim_{x\\to \\frac{1}{2}} \\sqrt{2x-1} = +\\infty$',' $\\lim_{x\\to \\frac{1}{2}} \\sqrt{2x-1} = -\\infty$','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH027','Cho hàm số $f(x) =\\frac{2x^2 -x -1}{x-1}$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to 1$ thì $\\lim_{n \\to \\infty} f(x_n)$ bằng','$\\frac{3}{2}$','0','4','$+\\infty$','A','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH028','Cho hàm số $f(x) = \\frac{x^3 +1}{x+1}$ Chọn dãy số (x_n) bất kỳ $x_n \\to -1$ thì $\\lim_{n \\to +\\infty}f(x_n)$ bằng ','0','$+\\infty$','-3','3','D','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH029','Cho hàm số $f(x) = \\frac{x^2-3x+2}{x+1}$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to -1$ thì $\\lim_{n \\to +\\infty}f(x_n)$ bằng','0','1','$\\frac{1}{3}$','A, B, C đều sai','A','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH030','Cho hàm số $f(x) =\\sqrt{x} -4$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to 4$ thì $limf(x_n)$ bằng ','0','-2','2','Một kết quả khác','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH031','Cho hàm số $f(x) = -x^2 + 7$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to -\\infty$ thì $\\lim_{n\\to +\\infty}f(x_n)$ bằng ','$+\\infty$','$-\\infty$','0','Một kết quả khác','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH032','Cho hàm số $f(x) = \\sqrt{4 -x^3}$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to +\\infty$ thì $\\lim_{n\\to +\\infty}f(x_n)$ bằng ','$-\\infty$','4','$+\\infty$','Một kết quả khác','C','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH033','Cho hàm số $f(x) = \\frac{2x^2}{\\sqrt{2}-x^2}$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to -\\infty$ thì $\\lim_{n\\to +\\infty}f(x_n)$ bằng ','$\\frac{2}{\\sqrt{2}}$','2','-2','Một kết quả khác','C','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH034','Cho hàm số $f(x) = \\frac{-10}{1-x^2}$. Chọn dãy số $(x_n)$ bất kỳ với $x_n \\to -\\infty$ thì $\\lim_{n\\to +\\infty}f(x_n)$ bằng ','-10','10','$+\\infty$','0','D','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH035','Cho hàm số $f(x) =x^2sin\\frac{1}{x}$ kết quả nào sau đây đúng ?','$0 \\leq x^2sin\\frac{1}{x}\\leq x^2$','$\\lim_{x \\to 0} x^2sin\\frac{1}{x} = 0$','$\\lim_{x \\to 0} x^2sin\\frac{1}{x} = +\\infty$','$\\lim_{x \\to 0} x^2sin\\frac{1}{x} = 1$','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH036','Cho hàm số $f(x) = \\frac{|x|}{2x}$. Kết quả nào dưới đây là đúng?','$\\lim_{x \\to 0}\\frac{|x|}{2x} = +\\infty$','$\\lim_{x \\to 0}\\frac{|x|}{2x} = \\frac{1}{2}$','$\\lim_{x \\to 0}\\frac{|x|}{2x} = -\\infty$','$\\lim_{x \\to 0}\\frac{|x|}{2x} = -\\frac{1}{2}$','B','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH037','Cho hàm số $f(x) = \\frac{cos\\pi x}{\\pi(1+x)}$. Kết quả nào dưới đây là đúng?','$\\lim_{x \\to 1}f(x)= -\\frac{1}{2}$','$\\lim_{x \\to 1}f(x)= -\\frac{1}{2\\pi}$','$\\lim_{x \\to 1}f(x)= \\frac{1}{2\\pi}$','$\\lim_{x \\to 1}f(x)= \\frac{1}{2}$','B','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH038','Cho hàm số $f(x) = \\begin{cases}2x-1 &x \\req 0 \\\\2 &x < 0\\end{cases}$ kết quả nào sau đây là đúng?','$\\lim_{x \\to 0}f(x)= \\lim_{x \\to 0}(2x-1) = 1$','$\\lim_{x \\to 0}f(x)= \\lim_{x \\to 0}(2x-1) = 2$','$\\lim_{x \\to 0}f(x)= \\lim_{x \\to 0}2 = 2$','$\\lim_{x \\to 0}f(x)= 2$','C','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH039','Cho hàm số $f(x) = \\begin{cases}2x-1 &x \\leq 1 \\\\3 &x > 0\\end{cases}$ kết quả nào sau đây là đúng?','$\\lim_{x \\to 1}f(x)= \\lim_{x \\to 1^+}3 = 3$','$\\lim_{x \\to 1}f(x)= \\lim_{x \\to 1}(2x+1) = -1$','$\\lim_{x \\to 1}f(x)$ không có giới hạn ','$\\lim_{x \\to 0}f(x)= -3$','A','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH040','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to 3} \\frac{x^2+9}{x^2+x+6}$ bằng','$\\frac{6}{5}$','$-\\frac{6}{5}$','$-\\frac{5}{6}$','0','B','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH041','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to 3} \\frac{x^2 - 4x + 3}{x^2+4x - 5}$ bằng','$-\\frac{1}{3}$','$\\frac{1}{3}$','$-\\frac{3}{5}$','$\\frac{3}{5}$','A','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH042','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to 4} \\frac{x^2 - 6x + 8}{\\sqrt{x} - 2}$ bằng','4','8','12','16','B','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH043','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to 5} \\frac{\\sqrt{5}-\\sqrt{x}}{x^2 - 25}$ bằng','$-20\\sqrt{5}$','$20\\sqrt{5}$','$\\frac{1}{20\\sqrt{5}}$','$-\\frac{1}{20\\sqrt{5}}$','D','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH044','Chọn kết quả đúng trong các kết quả sau : $\\lim \\frac{-3x^2 + 2x - 5}{2x^2 - 7}$ bằng','$\\frac{3}{2}$','$\\frac{2}{3}$','$-\\frac{2}{3}$','$-\\frac{3}{2}$','D','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH045','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to +\\infty} \\frac{3-4x}{5x}$ bằng','$-\\frac{4}{5}$','$-\\frac{5}{4}$','$\\frac{5}{4}$','$\\frac{4}{5}$','A','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH046','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to +\\infty} \\frac{2x^3 + x^2 -8}{5+4x^2}$ bằng','$-\\infty$','$+\\infty$','$-\\frac{1}{2}$','$\\frac{1}{2}$','A','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH047','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to +\\infty} \\frac{1 - x^4}{5x +3}$ bằng','$-\\frac{1}{5}$','$-\\infty$','$\\frac{1}{5}$','Cả A, B, C đều sai','B','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH048','Chọn kết quả đúng trong các kết quả sau : $\\lim_{x \\to +\\infty} \\left( \\frac{1}{x} - \\frac{1}{x+1}\\right)$ bằng','$+\\infty$','1','0','Một kết quả khác','C','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH049','Chọn kết quả đúng dưới đây ','$\\lim_{x \\to +\\infty} \\frac{x^2+1}{x-3x^2} = -\\frac{1}{3}$','$\\lim_{x \\to -\\infty} \\frax{1-x}{4x^2 +x +5} = -1$','$\\lim_{x \\to -\\infty} \\frax{\\sqrt{x-2}}{x} = 0$','$\\lim_{x \\to +\\infty} \\frax{-3x^3 +2x -4}{x^5 +5} = 3$','C','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH050','Chọn kết quả đúng dưới đây ','$\\lim_{x \\to +\\infty} \\sqrt{x-1} -\\sqrt{x+1} = -2$','$\\lim_{x \\to +\\infty} \\sqrt{x-1} -\\sqrt{x+1} = -\\infty$','$\\lim_{x \\to +\\infty} \\sqrt{x-1} -\\sqrt{x+1} = 0$','Một kết quả khác','C','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH051','Chọn kết quả đúng dưới đây ','$\\lim_{x \\to +\\infty} \\sqrt{x^2-5x} - x =\\frac{2}{5}$','$\\lim_{x \\to +\\infty} \\sqrt{x^2-5x} - x =\\frac{5}{2}$','$\\lim_{x \\to +\\infty} \\sqrt{x^2-5x} - x =-\\frac{2}{5}$','Một kết quả khác','B','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH052','Chọn kết quả đúng dưới đây ','$\\lim_{x \\to +\\infty}\\frac{1}{x} \\sqrt{x^2 + 5} = 0$','$\\lim_{x \\to +\\infty}\\frac{1}{x} \\sqrt{x^2 + 5} = 5$','$\\lim_{x \\to +\\infty}\\frac{1}{x} \\sqrt{x^2 + 5} = +\\infty$','$\\lim_{x \\to +\\infty}\\frac{1}{x} \\sqrt{x^2 + 5} = 1$','D','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH053','Cho hàm số $f(x) = \\begin{cases}-\\frac{1}{x} &x > 1 \\\\2x-3 & x \\leq 1\\end{cases}$ kết quả nào sau đây là sai?','$\\lim_{x \\to 1^+}f(x) = \\lim_{x \\to 1^+}(2x-3) = -1$','$\\lim_{x \\to 1}f(x) = \\lim_{x \\to 1}(2x-3) = -1$','$\\lim_{x \\to 1^+}f(x) = \\lim_{x \\to 1^+}\\frac{-1}{x} = -1$','$\\lim_{x \\to 1^+}f(x) = -1$','A','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH054','$\\lim_{x \\to 0}\\frac{\\sqrt{1+x} -1}{x} =$ bằng giá trị nào sau đây?','0','$+\\infty$','$\\frac{1}{2}$','$-\\frac{1}{2}$','C','gioihan','ghhs','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH055','Chọn kết quả đúng dưới đây ','$\\lim_{x \\to 0}\\frac{x-\\sqrt{x}}{\\sqrt{x}} =0$','$\\lim_{x \\to 0}\\frac{x-\\sqrt{x}}{\\sqrt{x}} =1$','$\\lim_{x \\to 0}\\frac{x-\\sqrt{x}}{\\sqrt{x}} = - \\infty$','$\\lim_{x \\to 0}\\frac{x-\\sqrt{x}}{\\sqrt{x}} = +\\infty$','D','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH056','Cho $y =\\left| \\frac{cos\\pi x}{x} \\right|$ kết quả nào sau đây là đúng?','Hàm số có dạng vô định $\\frac{\\infty}{\\infty}$ khi $x \\to +\\infty$','Giới hạn của hàm số là $+\\infty$ khi $x \\to 0$','$0 \\leq y \\leq 1$','Giới hạn của hàm số là $+\\infty$ khi $x \\to +\\infty$','B','gioihan','ghhs','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH057','Cho $y = \\frac{ x^2 -1 }{|x -1|}$ kết quả nào sau đây là đúng?','$\\lim_{x \\to 1}\\frac{ x^2 -1 }{|x -1|} = 0$','$\\lim_{x \\to 1^+}\\frac{ x^2 -1 }{|x -1|} = 1$','$\\lim_{x \\to 1^+}\\frac{ x^2 -1 }{|x -1|} = 2$','$\\lim_{x \\to 1^+}\\frac{ x^2 -1 }{|x -1|}$ không tồn tại','D','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH058','Cho hàm số $f(x) = \\begin{cases}x^2 + 1 &x < 1 \\\\a & x \\req 1\\end{cases}$ kết quả nào sau đây là đúng?','$\\lim_{x \\to 1^+}f(x) = \\lim_{x \\to 1^+}a = a$','$\\lim_{x \\to 1^+}f(x) = \\lim_{x \\to 1^+}(x^2+1) =0$','$\\lim_{x \\to 1^+}f(x) = 1$ khi a =1','$\\lim_{x \\to 1^+}f(x) = 2$ khi a =2','D','gioihan','ghhs','3',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH059','Để tìm $\\lim_{x \\to x_[0]^[+]$ với $x \\in (a;b)$ ta dùng dãy số $(x_n)$ bất kì nào dưới đây','$a< x_n <x_0$','$x_o< x_n <a$','$x_o< x_n <b$','$b< x_n <x_o$','C','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH060','Để tìm $\\lim_{x \\to x_[0]$ với $x \\in (a;b)$ ta dùng dãy số $(x_n)$ bất kì nào dưới đây','$b <x_n <x_0$','$x_o< x_n <b$','$a< x_n <x_0$','$x_o< x_n <a$','C','gioihan','ghhs','0',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH061','Chọn mệnh đề sai trong các mệnh đề sau:','Hàm số $y = x^3 +2x^2 -5x+7$ liên tục trên tập R','Hàm số $y = \\frac{3x+5}{x+1}$ liên tục trên tập R','Hàm số $y = \\frac{-4x}{x^2+1}$ liên tục trên tập R','Hàm số $y = sinx$ liên tục trên tập R','B','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH062','Chọn mệnh đề sai trong các mệnh đề sau:','Hàm số $y = tanx$ liên tục tại mọi x thuộc tập R','Hàm số $y = tanx$ liên tục tại mọi x khác $k\\pi (k \\in Z)$','Hàm số $y = tanx$ liên tục tại mọi x khác $\\frac{\\pi}{2} +k\\pi$ (k \\in Z)$','Hàm số $y = cotx$ liên tục tại mọi x thuộc tập R','A','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH063','Chọn hàm số $f(x) =\\frac{3x+5}{x+1}$. chọn mệnh đề đúng','$\\lim_{x \\to -1} f(x) =1$','$\\lim_{x \\to -1} f(x) = -5$','$\\lim_{x \\to -1} f(x) = 8$','$\\lim_{x \\to -1} f(x) = +\\infty$','B','gioihan','hlt','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH064','Chọn hàm số $f(x) =\\sqrt{x-2}$. chọn mệnh đề đúng','$\\lim_{x \\to 4} f(x) =\\sqrt{2}$','$\\lim_{x \\to 1} f(x) =\\sqrt{-2}$','$\\lim_{x \\to 1} f(x) =\\sqrt{-1}$','$\\lim_{x \\to 1} f(x) = +\\infty$','A','gioihan','hlt','2',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH065','Chọn hàm số $f(x) =\\frac{|x|}{x}$. chọn mệnh đề đúng','$\\lim_{x \\to 0^+} f(x) =0$','$\\lim_{x \\to 0^-} f(x) =0$','$\\lim_{x \\to 0} f(x) =0$','Hàm không liên tục tại x =0','B','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH066','Cho hàm số $f(x) =\\frax{x^2+3x}{x}$ chưa xác định tại x= 0 . Cần phải gán cho f(0) giá trị bằng bao nhiêu để hàm số liên tục tại x = 0?','$f(0) =-2$','$f(0) =-3$','$f(0) = 2$','$f(0) = 3$','D','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH067','Cho hàm số $f(x) =\\frax{x^2+5x}{x}$ chưa xác định tại x= 0 . Cần phải gán cho f(0) giá trị bằng bao nhiêu để hàm số liên tục tại x = 0?','$f(0) =-5$','$f(0) = 5$','$f(0) = 6$','$f(0) = -6$','A','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH068','Chọn khẳng định đúng dưới đây ?','Phương trình $x^3 + x+1 = 0$ vô nghiệm trên tập R','Phương trình $x^3 + x -1 = 0$ vô nghiệm trên khoảng (0;1)','Cả 2 phương trình $x^3 + x+1 = 0$ và $x^3 + x -1 = 0$ đều có ít nhất  một nghiệm trong khoảng (-2,1)','Cả A, B, C đều sai','C','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH069','Cho hàm số $f(x) =\\frac{cosx}{\\pi +x} -x$. Kết quả nào sau đây là đúng ?','Hàm số có tập xác định với mọi x thuộc R','$f(0).f(\\pi)>0$','Phương trình $f(x) = 0$ có ít nhất 1 nghiệm trong $(0; \\pi)$','phương trình $\\frac{cosx}{\\pi +x} =x$ vô nghiệm','C','gioihan','hlt','1',NULL,'11','0');
INSERT INTO `danhgiakienthuc`.`NHCHTOAN` (`id`, `noidung`, `dapanA`, `dapanB`, `dapanC`, `dapanD`, `dapan`, `dangtoan`, `dangbt`, `dokho`, `dophancach`, `malop`, `hinh`) VALUES ('GH070','Cho hàm số $y = f(x) =x^4 +x^2 -2$ Khẳng định nào sai ?','Hàm số đã cho liên tục trên R','Phương trình có ít nhất một nghiệm trong khoảng (0,2)','Ta có $f(-2)(2)>0 $ nên phương trình vô nghiệm trong khoảng (-2;2)','Phương trình $x^4 +x^2 -2 =0 $ có tối đa 4 nghiệm trong R','C','gioihan','hlt','1',NULL,'11','0');

/* HHKG */


UPDATE `danhgiakienthuc`.`NHCHTOAN` SET monhoc='toan';